# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043108 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.108"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.108/cli_0.43.108_darwin_amd64.tar.gz"
    sha256 "2cea98e4eadefd0f9b9bf3a2e2a3e8be0d6dcbe1f6133c6967a60668fa7e907b"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.108/cli_0.43.108_darwin_arm64.tar.gz"
    sha256 "169e571940aa9d378a2a39bf160254436c3026ba857c46be2fdec03e5c7cd288"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
