# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043118 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.118"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.118/cli_0.43.118_darwin_amd64.tar.gz"
    sha256 "7f887f41989628a184f4e406715889b74340bdbf47d2f2502c1b33d13982af8a"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.118/cli_0.43.118_darwin_arm64.tar.gz"
    sha256 "4403ad59f01e0f0a1465527163a5de882c685eabfd818997d1e314570591c293"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
