# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0367 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.7"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.7/infisical_0.36.7_darwin_amd64.tar.gz"
      sha256 "4f2e981a24bbfbedcc7946763621f56c1f8bcbf9610e0b334af6e3958e9680f8"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.7/infisical_0.36.7_darwin_arm64.tar.gz"
      sha256 "20d1809119c221cdd87a99669654ae8531127c5fe1b356fee4c663a2d030a71d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.7/infisical_0.36.7_linux_amd64.tar.gz"
        sha256 "c391dd355afc15717a58dcd432d290572fbec8f1b6ef44b7f6cbddb1c8760078"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.7/infisical_0.36.7_linux_armv6.tar.gz"
        sha256 "877c37a692b3b0ea7b8b448dc2cdc5407ab40d9ce9ea2a3152b14b6f3c2adfb6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.7/infisical_0.36.7_linux_arm64.tar.gz"
        sha256 "4e1dac01cc2702c0aa350359fbafbbf7dab64fbbe1c78b46ecb663725ec2a31b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
