# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT03618 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.18"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.18/infisical_0.36.18_darwin_amd64.tar.gz"
      sha256 "b69bed13ab6fb62ff27dc3cee3813d3a2c8225eafc15af19fe9acb7c491b6f23"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.18/infisical_0.36.18_darwin_arm64.tar.gz"
      sha256 "dcfddaa28cb258102dee9c706f8ba55242a5242e92faa74dd9f393beb985c7e9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.18/infisical_0.36.18_linux_amd64.tar.gz"
        sha256 "922ae941bbc4f2ac150414155db8c5c35fae376bf7826d4b3354e9b3c89ce430"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.18/infisical_0.36.18_linux_armv6.tar.gz"
        sha256 "5504b5d9f7837e78ed1ab0d96474e86d7b5abe3908d651e551151586eeded403"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.18/infisical_0.36.18_linux_arm64.tar.gz"
        sha256 "898c21beea0371fc4db999543baf832bd03b84212d2e41c700a6b8d784bfe640"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
