# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04350 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.50"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.50/cli_0.43.50_darwin_amd64.tar.gz"
      sha256 "377f9fefd2794e65e4f9d105ac226ad5c08a2da9ac60a59580afdf80c637286e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.50/cli_0.43.50_darwin_arm64.tar.gz"
      sha256 "aae2a2c5323518c469868cc2a1f49d3615e4a3274066714b92d623729fa94006"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.50/cli_0.43.50_linux_amd64.tar.gz"
        sha256 "e6908d6262c6937c248e16fb11b3c5703f5c1bf3e5ee4a40a4bfb4209e8e3f0d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.50/cli_0.43.50_linux_armv6.tar.gz"
        sha256 "4bbb613850d7f66deda15fee580ce5fa17eec228a9bc33a99aaae98d39711e14"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.50/cli_0.43.50_linux_arm64.tar.gz"
        sha256 "f2114ca2ca8bd2c293270e0bb316c0478113ae129f74c9f395e39254cdca451a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
