# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04360 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.60"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.60/cli_0.43.60_darwin_amd64.tar.gz"
      sha256 "bc5e51faa44705d8a3d384ef203dd8813a1e6569a490f0450c0cf833f25cac4f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.60/cli_0.43.60_darwin_arm64.tar.gz"
      sha256 "a5ef86966eba10302095bebe6d5c4d599c6bee6a7be4e3091f32b15dedf410d3"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.60/cli_0.43.60_linux_amd64.tar.gz"
        sha256 "709d1ef86479a2fd113c36a8fa291840d0f5b77731c2930958facfd00a31e7a0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.60/cli_0.43.60_linux_armv6.tar.gz"
        sha256 "ded7d76cf53d0aeea0708305f8790ad5f5976a46a56decdef51cd5cb5d2a8cab"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.60/cli_0.43.60_linux_arm64.tar.gz"
        sha256 "0ea8103d9122b1b17f107eef3fb714c89f6f8470edb21e33c16a3ab8983409ba"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
