# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0422 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.42.2"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.42.2/cli_0.42.2_darwin_amd64.tar.gz"
      sha256 "a98eda1a57f69f42dea8bf08f8a0fc2f6d67cbc45382eac089c644ec1df7e37f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.42.2/cli_0.42.2_darwin_arm64.tar.gz"
      sha256 "43a38ddaecf65d06c2e4a32134f0e4bd71a205153cc514f5950fa72b5dafe036"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.2/cli_0.42.2_linux_amd64.tar.gz"
        sha256 "88bc2bb4000b97299dcc78dd4cde5edebe0a67784c7b503aac3e97eb54e5517b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.2/cli_0.42.2_linux_armv6.tar.gz"
        sha256 "bc18bf111a3629bbb356a6750e4e595e78708eac4ca5ec5f95fdb996ddb79d17"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.2/cli_0.42.2_linux_arm64.tar.gz"
        sha256 "9497860b87d0512761baa7b388d3e12a1b702d4472645531745d0aca05946554"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
