# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0230 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.23.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.0/infisical_0.23.0_darwin_amd64.tar.gz"
      sha256 "09466e164a67e73b2c66888eb07085ab571a2b065e1f972edf4888cf72cd72ca"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.0/infisical_0.23.0_darwin_arm64.tar.gz"
      sha256 "67caa8eb3b034698453342f93b366aa999bb7ddbc5fe163234db976b72b4ca50"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.0/infisical_0.23.0_linux_amd64.tar.gz"
        sha256 "012a7ebc8c29b9e0ce9885d36bfa1cee16bf88d65ec525c4c96581c80471d034"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.0/infisical_0.23.0_linux_armv6.tar.gz"
        sha256 "39da071dc883e1c3fb4a09678e4aa1c2a89b28c52048aaf2425be876a2e74c07"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.0/infisical_0.23.0_linux_arm64.tar.gz"
        sha256 "420a0285d262fe45f61f8933d7aee68d86d38035b4844805411af061edc6e8df"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
