# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0182 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.18.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.2/infisical_0.18.2_darwin_arm64.tar.gz"
      sha256 "bfd81ae5d159e60f7bc5fdd4df9c25306cfa382f13490a52d682abe299d2ca5a"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.2/infisical_0.18.2_darwin_amd64.tar.gz"
      sha256 "7c5249b0e6efab380a7d3fc896864e501e8f579150b6108df60f69a9908770b9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.2/infisical_0.18.2_linux_amd64.tar.gz"
      sha256 "7f6ab7b2d8e544616aa6c78195273c8e02dcf110afac4fa271cf38ddaa7e15bb"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.2/infisical_0.18.2_linux_armv6.tar.gz"
      sha256 "ca6966d08efb57609f91b654f2e5566e38f753e3c51369a52e1eab12dc415479"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.2/infisical_0.18.2_linux_arm64.tar.gz"
      sha256 "314b4f20589ffd52b707a35c37dc91745067bfe8620fae6dace9631813eff321"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
