# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04330 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.30"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.30/cli_0.43.30_darwin_amd64.tar.gz"
      sha256 "302afa9e00cf0cc11abf498794a063c287d1e8d90b8e3de6d68a7480af525cf9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.30/cli_0.43.30_darwin_arm64.tar.gz"
      sha256 "b42e8885c9330bf98856906a977bb5dfe1dfb617f67f12e1446d4a9434bfa992"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.30/cli_0.43.30_linux_amd64.tar.gz"
        sha256 "b879322f15ffc3cf28db540b5d1ed81a167de44ad6dbd9eb01a8370f54235ced"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.30/cli_0.43.30_linux_armv6.tar.gz"
        sha256 "5a65843089dd1bf105e988d7b82d6abf9856957589718e6f66066ed6aa3709e9"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.30/cli_0.43.30_linux_arm64.tar.gz"
        sha256 "e048d20df4d2a0e30d9cd153dab64c2a489c3b430af514cfbf6297c565a3e407"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
