# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04333 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.33"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.33/cli_0.43.33_darwin_amd64.tar.gz"
      sha256 "1fb7c0a2287acdd6ad8114947f01faa985c0a8bd74d299b44199edbb0aa3eb3a"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.33/cli_0.43.33_darwin_arm64.tar.gz"
      sha256 "0ae8959418298737ff0a7b60dba578096ed5d0abba632025128b6060514c566f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.33/cli_0.43.33_linux_amd64.tar.gz"
        sha256 "0c67880039002feeabf016b051c9484fabea5b37665e7139f158487963749cde"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.33/cli_0.43.33_linux_armv6.tar.gz"
        sha256 "3dd7b7fbee53d6f518c22719c2450c98074ac1f9b5ba56b7d879c9ba52242d56"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.33/cli_0.43.33_linux_arm64.tar.gz"
        sha256 "222bdf09bb4fdf42c36ac3bbf63ddc804d7a9f983b7fe51fab3e929d8e1c2098"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
