# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0370 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.37.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.0/infisical_0.37.0_darwin_amd64.tar.gz"
      sha256 "6b4faad7c6459ef8617d5359df441b487d9ecc6262236b783712cd31cf816774"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.0/infisical_0.37.0_darwin_arm64.tar.gz"
      sha256 "b34cd4ea1b29cbfdce4eddc3fe92273876ce8e0d491a5e7b1028cb7df1bbc5ec"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.0/infisical_0.37.0_linux_amd64.tar.gz"
        sha256 "b7e68dbcf4c4815e4bea586cc8003ab63af3230537920521c1e559a107687366"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.0/infisical_0.37.0_linux_armv6.tar.gz"
        sha256 "939deaeaad72e024e4526d8678f0f244157bd6a59e81749996dc7168ca8b05f1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.0/infisical_0.37.0_linux_arm64.tar.gz"
        sha256 "7422498aa104749c5229659093fe736fc7c9f6a85f5797fb1f974b69aa57f6ee"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
