# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04194 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.94"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.41.94/cli_0.41.94_darwin_amd64.tar.gz"
      sha256 "ac9d0157941257e94d6b48298819f0bacbec012e118a0c902fa3783571383760"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.41.94/cli_0.41.94_darwin_arm64.tar.gz"
      sha256 "6c24833d64c2aef592d8fd8ae12494d79ac629710e404b60836d6402197690df"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.94/cli_0.41.94_linux_amd64.tar.gz"
        sha256 "245eea9b6dc5fdda5689ab906f5a2ccce0a0aff4196d47404a1cd4e618548fcd"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.94/cli_0.41.94_linux_armv6.tar.gz"
        sha256 "b5cab7bde7dc916bb30bdcf26ad2a1abf4ed871f186e6a9ecc0c83ee52d76b19"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.94/cli_0.41.94_linux_arm64.tar.gz"
        sha256 "19aca6855de81a6823da6bc249b8db4c5085da430f20ae591759097980c9b982"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
