# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04344 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.44"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.44/cli_0.43.44_darwin_amd64.tar.gz"
      sha256 "89f53a89cf2bad5161d7be1f73f12a53a9403f071fff30f7f2c50e347756e686"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.44/cli_0.43.44_darwin_arm64.tar.gz"
      sha256 "bd3db1e3665a9e97c90ef2413dcc9f5631f8e45df539b2c70e0becdeeaa35c9c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.44/cli_0.43.44_linux_amd64.tar.gz"
        sha256 "bd046cba5f8901bb868e1706061cf0d87cf2f2c5ac9289c8fe78b079252f6918"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.44/cli_0.43.44_linux_armv6.tar.gz"
        sha256 "345b4fc41bbfc5021283701a715dc9db003ef863ea9e83b3c310955c1b1bb27e"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.44/cli_0.43.44_linux_arm64.tar.gz"
        sha256 "88919c7aff3a6804dfee1a7da6d32f13d5039e0502fdf7b9999366b6416c449b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
