# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04364 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.64"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.64/cli_0.43.64_darwin_amd64.tar.gz"
      sha256 "349d870ed070776696f00dda58b4ab6b4ff3af19ed2c7bdd3e1b380f386ab7b3"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.64/cli_0.43.64_darwin_arm64.tar.gz"
      sha256 "9e11f882ce83f1504627e380ba4ddf25a393797ba193380a3a76b32be0be37a6"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.64/cli_0.43.64_linux_amd64.tar.gz"
        sha256 "1860d89e0f61b0730a068ae44f15b4fd9f2fcd61a8b8509e038c27e2704983dd"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.64/cli_0.43.64_linux_armv6.tar.gz"
        sha256 "14c83ea4dd3344c42c45ea8fae8a28d1efdbb24576247ac452ec00d318d706f2"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.64/cli_0.43.64_linux_arm64.tar.gz"
        sha256 "44f3cce9c27c549f2311ff3d09b137b0e3fb791fc17dd461a958875007153e4a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
