# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT03617 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.17"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.17/infisical_0.36.17_darwin_amd64.tar.gz"
      sha256 "4f0a737784e6142bd95b050c1eb42135459e0f3ddeb8a2156e7298c0cd702ad8"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.17/infisical_0.36.17_darwin_arm64.tar.gz"
      sha256 "36d1a575a564c38d1630907dd62671753afac3cbdb332c8442298193d95d48c2"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.17/infisical_0.36.17_linux_amd64.tar.gz"
        sha256 "faa19dc4a312b5f6cb899279d9ac72648d105e68d7e5aa1330260394cce58306"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.17/infisical_0.36.17_linux_armv6.tar.gz"
        sha256 "2f4bed1a04c53d207c5c1d08bd7fcf64bd5b50d60a9173c4ec24899d23a6e490"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.17/infisical_0.36.17_linux_arm64.tar.gz"
        sha256 "64b738d43976178f97d4fd4a03151cedb19388730cf6d417d3a1ab5d2270e515"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
