# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04370 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.70"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.70/cli_0.43.70_darwin_amd64.tar.gz"
      sha256 "ab785502b03a9cf53ca8df17581e5f0677508757395b01ce1bea8d9b4b187807"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.70/cli_0.43.70_darwin_arm64.tar.gz"
      sha256 "e6401eec1ebe77f1152efc025a21f5decf0997a46cb186320b23829e4e3a16bd"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.70/cli_0.43.70_linux_amd64.tar.gz"
        sha256 "62b67c79a0516ffad87b59df19a7fe6ce415e516c06b1dcd0dd08dfdd2bcf54f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.70/cli_0.43.70_linux_armv6.tar.gz"
        sha256 "f3175da4007af740d4d197e83673afdcee084ac120edcb62ce4f4001b02a8ccd"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.70/cli_0.43.70_linux_arm64.tar.gz"
        sha256 "544c7d833f31a93cc42a7012c393ea5544d7309612046e0b92a7899edb5c7316"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
