# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0200 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.20.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.0/infisical_0.20.0_darwin_amd64.tar.gz"
      sha256 "e92abccd8971b8b1b135f9c95878b6a172f3dce218f8f5d1ae0fff8b40b01f7c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.0/infisical_0.20.0_darwin_arm64.tar.gz"
      sha256 "d33e19849874c769d8118e43c11c39e4a05339f57c476e4350bda0ae399ed87e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.0/infisical_0.20.0_linux_arm64.tar.gz"
      sha256 "4fa7f6feddf98ca7f88492e03be2744b76bdb77dd40fca7fa63e3efd8612d7b7"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.0/infisical_0.20.0_linux_amd64.tar.gz"
      sha256 "a9acdf99d0e9e4639415f3d769592f08d64d1bc81c333f06bc1c2044e1d80266"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.0/infisical_0.20.0_linux_armv6.tar.gz"
      sha256 "e33d10ae8dfb49de1c43b1840f27ce68e4765101c013b54f29060cf8e5956487"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
