# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04341 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.41"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.41/cli_0.43.41_darwin_amd64.tar.gz"
      sha256 "dbaf5270b5236c91b96134874e33473efd727e33b9e5bb85256b41d6d1aee024"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.41/cli_0.43.41_darwin_arm64.tar.gz"
      sha256 "944c0ab9f99ffc7e09761472ccb0e34da02ca4e86fda0346eba81654f46ede87"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.41/cli_0.43.41_linux_amd64.tar.gz"
        sha256 "43af0910a0ccd62d19d0092f42f27bdc734bac9105e12a5109af7bea7a5bd160"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.41/cli_0.43.41_linux_armv6.tar.gz"
        sha256 "0799f32a70cd4bc1c45f8d234a705427c87af43e2ef3b901f68cc2c253e5ee20"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.41/cli_0.43.41_linux_arm64.tar.gz"
        sha256 "5d697505cc8ce7eb3483887aa535a2c026251915a2de0ade7966414023c1dd33"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
