# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04387 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.87"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.87/cli_0.43.87_darwin_amd64.tar.gz"
    sha256 "d21ed4ea59e5f9ccedd79dc7dabcec0c03cbadf27f75a1e8c2d0e02185b1cf60"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.87/cli_0.43.87_darwin_arm64.tar.gz"
    sha256 "1a29fa5f205fd47f6d7291e62bc05ee01b727e458d755d917761437eadbf8d68"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
