# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0402 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.40.2"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.2/infisical_0.40.2_darwin_amd64.tar.gz"
      sha256 "58db4dffc28eafdecad213969f1018298fbf02c5709b794e1b4af84ce489cb2e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.2/infisical_0.40.2_darwin_arm64.tar.gz"
      sha256 "461bda5644dba3354d4d6fa95b0f73327da279ba85361fd09a69fa45cdba1b28"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.2/infisical_0.40.2_linux_amd64.tar.gz"
        sha256 "36fede064a568c7f1df9bf04a9fb8f1de176f60c29eb0cfebe6fdcf278a325bb"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.2/infisical_0.40.2_linux_armv6.tar.gz"
        sha256 "0108ce388be0aa3798f8bea05ae6918bcbb74bf0de84e8f178df56fa0d6ed862"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.2/infisical_0.40.2_linux_arm64.tar.gz"
        sha256 "6ebe7ad04ba335988a74fd19007cf00f0b646dc85c32541c4ef8be53f627cdb9"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
