# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT03616 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.16"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.16/infisical_0.36.16_darwin_amd64.tar.gz"
      sha256 "cd1bb4947d9a62779e7e9516b681276daac9db48c7c200e278450b438636d490"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.16/infisical_0.36.16_darwin_arm64.tar.gz"
      sha256 "54eef45a76f5a46bccace3f758f1edf7a89d94785c2c25c9bda395d4ecd3b1ff"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.16/infisical_0.36.16_linux_amd64.tar.gz"
        sha256 "6a2e0ec5ab648008f3176ca578ee3ce8a1f0c50214a916661400f2db2ae9f7ad"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.16/infisical_0.36.16_linux_armv6.tar.gz"
        sha256 "3c0568cf300d1c24f079f89d147a864e9af76dfe9e503c4f4eecc4d52f9a46b6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.16/infisical_0.36.16_linux_arm64.tar.gz"
        sha256 "d74c5d9b5d4588e5b8f252570aa7be9c709d36040af62f797513de0775d2a141"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
