# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04339 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.39"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.39/cli_0.43.39_darwin_amd64.tar.gz"
      sha256 "ba310d7e0b7e6542e6f590243bc98e3cbee3ab5ed0db73b1b45e3828d4a6feed"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.39/cli_0.43.39_darwin_arm64.tar.gz"
      sha256 "a38e2cd40eb6d149467a598b76b084ad50513b2b9896306059bd79cf6582b138"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.39/cli_0.43.39_linux_amd64.tar.gz"
        sha256 "b46afb5cb4c5a6fd53151b09ce6da8ff8a57f5c64b944135d5e69a410cc5ce02"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.39/cli_0.43.39_linux_armv6.tar.gz"
        sha256 "c8dd5609ddd96c397c65ed1f1a5a28f3bc6748547da03545333e1fdf42d5a9e9"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.39/cli_0.43.39_linux_arm64.tar.gz"
        sha256 "482a992e04baf90d5d816b8366516a3d3c41d7bf43e82a134c806cafc570ebca"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
