# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0140 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.14.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.0/infisical_0.14.0_darwin_arm64.tar.gz"
      sha256 "53e979308ec4016d8da6ec3d999c652ccf30f1c879f72780ba2fcafabb155a41"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.0/infisical_0.14.0_darwin_amd64.tar.gz"
      sha256 "d6896dc66cb0c511b0672546ae0fab7f5567a0d0811a4f60e3caf366446a6ad4"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.0/infisical_0.14.0_linux_arm64.tar.gz"
      sha256 "f120953000bdcef14fe07e364a13daf599b87b98072a3a0654e0b9ca8e61e771"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.0/infisical_0.14.0_linux_amd64.tar.gz"
      sha256 "0563ab949944ea2798dbfaf0d51140d7abdcd64a2c72155791205dfc4ec19c68"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.0/infisical_0.14.0_linux_armv6.tar.gz"
      sha256 "8844a3faace6349d59b3a0f2a262daafde8ff5b7c0772dc0badc64824b070df4"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
