# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04338 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.38"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.38/cli_0.43.38_darwin_amd64.tar.gz"
      sha256 "21f05b2412b5ef22eca38b33eb70aac021420d48a482862e1d35ef0dad2f2db9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.38/cli_0.43.38_darwin_arm64.tar.gz"
      sha256 "6a20649d5f3a443a42352d415bb12798aa362f18f81eae90943b27ce8d4c5d70"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.38/cli_0.43.38_linux_amd64.tar.gz"
        sha256 "27e693b2a379c87497d5d861f1823671a8ab6fbe9464f5bbc5610ef7ce63dd84"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.38/cli_0.43.38_linux_armv6.tar.gz"
        sha256 "eac9ed2391d6852dd7e69dd65876f1bc0debb5ccc7893d38d62edadc977b0b94"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.38/cli_0.43.38_linux_arm64.tar.gz"
        sha256 "8dee889823efa3530932af0483993c9ac908522e07bea6a7497e87308fda48b1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
