# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04349 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.49"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.49/cli_0.43.49_darwin_amd64.tar.gz"
      sha256 "0a77b9fe471a9e53e79b7db63ad0cba0cfbf40331f86c2fdfd26a9bc62b4c5c6"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.49/cli_0.43.49_darwin_arm64.tar.gz"
      sha256 "34c1c5aacf10209fdbab1b1287566c1f0e456e516d596ff4b451b642c6d21f49"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.49/cli_0.43.49_linux_amd64.tar.gz"
        sha256 "db2babf0390055871f5b46a993ab2c827bf57f5d18ab3f0ec9b8990d37018f2f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.49/cli_0.43.49_linux_armv6.tar.gz"
        sha256 "a71fa03b915f8becd8ac4fe138a50770e4be2cd53f92230575870fe2b74e6739"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.49/cli_0.43.49_linux_arm64.tar.gz"
        sha256 "8e5d153408bf358c90aa6b89fce65cd3fcbdf2831d4279388a6afca9eecefd4c"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
