# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043119 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.119"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.119/cli_0.43.119_darwin_amd64.tar.gz"
    sha256 "d5f2a284b29204eb47cc37173a4fa3819bbdf1ae18cc02eeb3c4c9db1809ab51"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.119/cli_0.43.119_darwin_arm64.tar.gz"
    sha256 "8a26c1953065f7eb364b185b95f5ff3fad7937336953c23c3ff8666d0e4a8872"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
