# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04191 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.91"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.41.91/cli_0.41.91_darwin_amd64.tar.gz"
      sha256 "9ba667f3dfe0cf852de4fbdd4168018eab6dfd287b6efdabff464778983e72d9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.41.91/cli_0.41.91_darwin_arm64.tar.gz"
      sha256 "a4e445c911dce7ffa7ddf651ba31cf3562376f5804ea5fd78a8d2b03345e47bd"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.91/cli_0.41.91_linux_amd64.tar.gz"
        sha256 "27ec5960a273753973ac2f27784ee4230894b033f3ddedef29e3f36326ae46e0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.91/cli_0.41.91_linux_armv6.tar.gz"
        sha256 "6f5177b7056d2810c39ae10238e00aa00863789fc0af25018e4a3b9101692e99"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.91/cli_0.41.91_linux_arm64.tar.gz"
        sha256 "b7380baca0b7142006d122836a8f0797c3e663ea8a5816aa463f122f219a9353"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
