# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0423 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.42.3"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.42.3/cli_0.42.3_darwin_amd64.tar.gz"
      sha256 "bf80f93a21ce9a6e99a956191b0cc462231062a701fa813902d385247ff419dd"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.42.3/cli_0.42.3_darwin_arm64.tar.gz"
      sha256 "67707148616b36201fafcfc8e2df81769f5dd290f48c11de6b78d94021dc5cdc"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.3/cli_0.42.3_linux_amd64.tar.gz"
        sha256 "e8083ad7a643830081ab4284477215d3abf32b8f1902d5d5df0ffe9ee8c5f229"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.3/cli_0.42.3_linux_armv6.tar.gz"
        sha256 "46e87425a3414a9ad50240edd4964a9ce0ce73e94aee6121c7ccdcda8c9a3d3f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.3/cli_0.42.3_linux_arm64.tar.gz"
        sha256 "7b0978ae9f99636695ded6ccd2110835560f2b39bacfd99e2f7b9d4bbff64dba"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
