# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04391 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.91"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.91/cli_0.43.91_darwin_amd64.tar.gz"
    sha256 "06b43c820fc7a474a9e5cf64d29f853e30db88fbc112cfb7110dc97e911db9f7"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.91/cli_0.43.91_darwin_arm64.tar.gz"
    sha256 "0da3a0474481ec0949782d0054a864aac7bdbcbfd109db42312871f992eba238"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
