# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04371 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.71"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.71/cli_0.43.71_darwin_amd64.tar.gz"
      sha256 "6a380fc178edd885c91da463e64f27eaed4d2afc1c2963c83d30622cca0832fa"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.71/cli_0.43.71_darwin_arm64.tar.gz"
      sha256 "5b3174a4dacb9a76e014907d0fcaeafb178fe40d8c4c87a0493e1d730dab2cee"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.71/cli_0.43.71_linux_amd64.tar.gz"
        sha256 "ac94fc9f01584923d1c13225effb6114fb9a92d2f761c3617e4e0c971130e56b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.71/cli_0.43.71_linux_armv6.tar.gz"
        sha256 "29a0a966f0974f20a0ce90b8859d1bb64ed4b35cd736f8f580e70bfb3bda76f0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.71/cli_0.43.71_linux_arm64.tar.gz"
        sha256 "82f5c6b23b1d4b4e9cd54349875c66088ff477c09f8b4955a5815fe0171e8515"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
