# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0424 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.42.4"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.42.4/cli_0.42.4_darwin_amd64.tar.gz"
      sha256 "83cfa51bd2ec3d8b96ce9055fbed68bc4b1adb7d2978e7e09284da23de09c454"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.42.4/cli_0.42.4_darwin_arm64.tar.gz"
      sha256 "33d5b07bcbcdf7adc96d54eb712a2655c03602a96b3e0be170263ab5ab02a94c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.4/cli_0.42.4_linux_amd64.tar.gz"
        sha256 "2cb5d8dc7941b06b0f2437601e7564c5b74bce8d1e1707adc35ec0f54ac8f0d1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.4/cli_0.42.4_linux_armv6.tar.gz"
        sha256 "48a58675faf615fcbacaf074ab5f6f501fe3ad1448a6ba1760d591b1d749f08d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.4/cli_0.42.4_linux_arm64.tar.gz"
        sha256 "df9af90e552388c5e4eb52baab68d53443d137c325635842c89da0cffc2f4416"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
