# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0131 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.13.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.13.1/infisical_0.13.1_darwin_arm64.tar.gz"
      sha256 "cb8e7ee67564d41f2c78a706acbb771ff00ec4c9b4ce29302c800e6ff54d1cda"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.13.1/infisical_0.13.1_darwin_amd64.tar.gz"
      sha256 "1c4d2701b31eec154d0e24805c5285ca5ec3c5c4223f041105ea450976c27a9f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.13.1/infisical_0.13.1_linux_arm64.tar.gz"
      sha256 "49ddcbefbb6b134bb5d9e90934afdbd42245832e6bd9ffab367f1bb79b55b3b6"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.13.1/infisical_0.13.1_linux_amd64.tar.gz"
      sha256 "c74f9174a00bcb8914f2670701c6b7878ed882fc844efce722add621c28ef003"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.13.1/infisical_0.13.1_linux_armv6.tar.gz"
      sha256 "3cd115f48ca2dc689f60768c214062453482936a2d343190d87f6d4a3b661c86"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
