# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT03619 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.19"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.19/infisical_0.36.19_darwin_amd64.tar.gz"
      sha256 "f916cabb2c2c2f05880d5be45d039ac4e50dc08ee962dfec6c533f3874c9dc6d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.19/infisical_0.36.19_darwin_arm64.tar.gz"
      sha256 "9536fd2623185b512348b8a517d4ed980a33e78c270c7c6a7273bb51e02c6e91"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.19/infisical_0.36.19_linux_amd64.tar.gz"
        sha256 "bd1ed7047a654cdad4917f9c253f77c2c5a278b5a6dfa43c4187773d74ce3665"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.19/infisical_0.36.19_linux_armv6.tar.gz"
        sha256 "d19570dc2eadbc4f0f7980009faf47d9b44344db524848f89b99505265fad79a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.19/infisical_0.36.19_linux_arm64.tar.gz"
        sha256 "2a545cb97e15d81886558c59a1c0974bd5fa4d59e57dc010717cd57307f9cca8"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
