# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04347 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.47"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.47/cli_0.43.47_darwin_amd64.tar.gz"
      sha256 "27090571f0bb4509d6c84a851464099edfd0d0240f2f3333c1a9e8f4184544e8"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.47/cli_0.43.47_darwin_arm64.tar.gz"
      sha256 "e0310491a110edc477233b94345ed1a89bc16baf4a3b4313d73ea721633199bf"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.47/cli_0.43.47_linux_amd64.tar.gz"
        sha256 "ed90541afe7d7c9279478e90c05eccf8c97d1c99eb871edf8ea20fbc1359b87f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.47/cli_0.43.47_linux_armv6.tar.gz"
        sha256 "fff116985292820fc5f4f5360f807e64ba4101054cfe80213d6f965fee4fb202"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.47/cli_0.43.47_linux_arm64.tar.gz"
        sha256 "08110ea1fb28c156e40c8cf48d569463f110d0d28ca8b68d70b2eccf060d9406"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
