# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0371 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.37.1"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.1/infisical_0.37.1_darwin_amd64.tar.gz"
      sha256 "ddfa09f766cb4439a4edc2b43c4609d03aafbc1183f5ab4f74dac6a069695773"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.1/infisical_0.37.1_darwin_arm64.tar.gz"
      sha256 "c8ba275f205b60759839bff13cd1cc658591b9e0bf3b86c47cec9917ebc3f3bd"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.1/infisical_0.37.1_linux_amd64.tar.gz"
        sha256 "2a90d3bf18609456a2a1daf370fe41c19418c96202c4b6638eed736e511068b3"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.1/infisical_0.37.1_linux_armv6.tar.gz"
        sha256 "55506ae9a7cf8da105054accb3c9e7cc1bfc77efa2ee9b7cd3f8bb1cd5a0d29c"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.37.1/infisical_0.37.1_linux_arm64.tar.gz"
        sha256 "65d87e8517f4627012444668c691043d7f7c7d7ba2498d668ade4f0d47d5e630"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
