# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0222 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.22.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.2/infisical_0.22.2_darwin_amd64.tar.gz"
      sha256 "1bbbe892132ae30efcd4c9317984e895cd804c53b018b25e6785c84b4135879b"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.2/infisical_0.22.2_darwin_arm64.tar.gz"
      sha256 "6ccc37f45b0be2d8c017f3bf63b5e0da9c55396eb8a972cf6c38dabbc8289d8d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.2/infisical_0.22.2_linux_amd64.tar.gz"
      sha256 "a11464bf4c78dea851cec4f070ff7ce799003a281f9f5dd63c01a3ec8cdc9b76"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.2/infisical_0.22.2_linux_armv6.tar.gz"
      sha256 "fbe632113af6c5f6ad35af7ca179487bd7e79db857113ac2f1c5bc937c20e9a7"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.2/infisical_0.22.2_linux_arm64.tar.gz"
      sha256 "257cd301f48d14f971337fef9be98c77ca684fcd1be97a595d72d286c1871a76"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
