# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0425 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.42.5"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.42.5/cli_0.42.5_darwin_amd64.tar.gz"
      sha256 "c10fad14f07b322f9715898acd3938320ec40875c81495efae674d4ba427886e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.42.5/cli_0.42.5_darwin_arm64.tar.gz"
      sha256 "563c1c9e7b9a44d985d1f8a9c2195b5fc426d4ad2520af91a49fc12846739c68"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.5/cli_0.42.5_linux_amd64.tar.gz"
        sha256 "2c7ce329688cf430eeefcdc6ecb571a6511ebaf995a59bb96c70649d67a3db03"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.5/cli_0.42.5_linux_armv6.tar.gz"
        sha256 "b114289baaf7d9f82c400b5bcb536bec8409a8d690b442ff84032a86479f2adb"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.5/cli_0.42.5_linux_arm64.tar.gz"
        sha256 "72d5ae9f10bb3dfaf7ad335906122baf6d180a6e118d9b07628355c737cb6e42"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
