# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0365 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.5"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.5/infisical_0.36.5_darwin_amd64.tar.gz"
      sha256 "5b40f0566a1a000ac93a224e1d8bd0826f5510f07dab92448b3a122ff2afb9fa"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.5/infisical_0.36.5_darwin_arm64.tar.gz"
      sha256 "6a3ca457b1e5b70c42cdf59623e22ef4d66a46ac27c0ec03fb88600051ea8f3d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.5/infisical_0.36.5_linux_amd64.tar.gz"
        sha256 "3b9475c338125c5a28debabd4c9925058702c32224b4e272789d799ddecffdca"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.5/infisical_0.36.5_linux_armv6.tar.gz"
        sha256 "8d868d1b3ceedbb6159c7939e4718f5bc7e3caf12ea3893c6159846edec02233"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.5/infisical_0.36.5_linux_arm64.tar.gz"
        sha256 "b290f1815199909f634f10bcf1b8027977b73cb5966f459f1c5dcd7d4384ae6d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
