# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04314 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.14"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.14/cli_0.43.14_darwin_amd64.tar.gz"
      sha256 "59a0047324feaa40ffcc003731daccabdca8296248d583bf42d569e2ec1e6c12"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.14/cli_0.43.14_darwin_arm64.tar.gz"
      sha256 "4cb407a1d2cb279c05fa3ff1e7e1cf993f6517dd9d06e4f8e70639a7023518d8"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.14/cli_0.43.14_linux_amd64.tar.gz"
        sha256 "a0aa0e5c77abf477b21021d87ad4d6ee1a76446cb971771c89ecbcba2c3104b7"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.14/cli_0.43.14_linux_armv6.tar.gz"
        sha256 "7ab0e5253fc3751b5cb10237c80dbae24a822a03ae18a113fcf63f626b8bce60"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.14/cli_0.43.14_linux_arm64.tar.gz"
        sha256 "2f72eb16bcacd143d8b2aba6358f619759c34b2ff9f42ed951be589e2d5f7efc"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
