# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04335 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.35"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.35/cli_0.43.35_darwin_amd64.tar.gz"
      sha256 "abf699cb5930dcb575e189e7f17c4335295186a1a5c2d3369b22a8cfced3f3c2"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.35/cli_0.43.35_darwin_arm64.tar.gz"
      sha256 "4c0eac94352ce9cff06c35452a8c7c6451a65ba83c2b1b09816d724d85883d31"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.35/cli_0.43.35_linux_amd64.tar.gz"
        sha256 "2320dc6d933f7b4a44e948d1a87a9be649e99f748d6ab6a5dd621c23e639c568"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.35/cli_0.43.35_linux_armv6.tar.gz"
        sha256 "dee60e174f13bae5f6cc42c0cdf5123840e9af83cbc3657a7cd57a80bce6bb4a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.35/cli_0.43.35_linux_arm64.tar.gz"
        sha256 "40e2fcc2f8c53643a5011e8dbb6e09112484f50f3f465ddea894c78e3ce177b4"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
