# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04358 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.58"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.58/cli_0.43.58_darwin_amd64.tar.gz"
      sha256 "024ceeca4abf6425ccf27bebe9b405418b0888b48be92784240979d8dfe2f483"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.58/cli_0.43.58_darwin_arm64.tar.gz"
      sha256 "d5fb891962b900b703076d28abc2d66046b74f5c8694633dc6cb8927b1b13984"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.58/cli_0.43.58_linux_amd64.tar.gz"
        sha256 "2799938a0cddff3341e1b14bc1f194bfd5d3aa7f1e3d395e384b10308f4eb52f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.58/cli_0.43.58_linux_armv6.tar.gz"
        sha256 "13c0e6735f3a89a99045e0e8d44f2d0f547895ff9b8a1145ab6f8c0914ed2a0f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.58/cli_0.43.58_linux_arm64.tar.gz"
        sha256 "aec106f1536ab370f9ba432c7e932b53a976351095920fb1a251de0cb2fdf566"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
