# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0283 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.28.3"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.3/infisical_0.28.3_darwin_amd64.tar.gz"
      sha256 "7431e421d28c8b3aa617459f551a08f9a02748e3caa042b323889c7137b1c96b"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.3/infisical_0.28.3_darwin_arm64.tar.gz"
      sha256 "a41081cedc4db58c66ab4d7e8a266c99ace87ed8c75da3aeecf71a64922564a4"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.3/infisical_0.28.3_linux_amd64.tar.gz"
        sha256 "38f737f8231d46878d3e90dd7b41b46573698d1b4debd7aeca08f19f619bda8c"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.3/infisical_0.28.3_linux_armv6.tar.gz"
        sha256 "5ab8631eae7349a03f564d949984fe7e091fd6e6e04858b2e8eea8a1a7c20c20"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.3/infisical_0.28.3_linux_arm64.tar.gz"
        sha256 "61782713d1d4b6951e99a96dbcdac32092c65eca1cce0185102cb3ff675012ec"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
