# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04316 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.16"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.16/cli_0.43.16_darwin_amd64.tar.gz"
      sha256 "56573a7006e7ff8e0512b99ca590e98c2507c27bd8c60f798e3f03918012ca85"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.16/cli_0.43.16_darwin_arm64.tar.gz"
      sha256 "f5d5742207bf7a73cf9d28ca348ea309dca5db00333021ce2c8822be70989594"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.16/cli_0.43.16_linux_amd64.tar.gz"
        sha256 "91343a055acbc776fd152e7f023a178abd19b2d7daad467e9f390c9337018eac"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.16/cli_0.43.16_linux_armv6.tar.gz"
        sha256 "02bab7839f21f86c55f6cfcfc3fb48cb7807ea29f8f478fb16edf1db3ab71a00"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.16/cli_0.43.16_linux_arm64.tar.gz"
        sha256 "510e716c6ada21907a7ad0150ac05d1efd6e0b4812d3a353e4bdf6fc5d313ece"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
