# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0341 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.34.1"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.1/infisical_0.34.1_darwin_amd64.tar.gz"
      sha256 "1949529e4ab4eebaf1980414273917a4fa53b3d6d430bccd9ba542119dde0c52"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.1/infisical_0.34.1_darwin_arm64.tar.gz"
      sha256 "15b377b6f09c943a242ba75683a53acd0f4d593678c7a53f6e7f243739c22f59"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.1/infisical_0.34.1_linux_amd64.tar.gz"
        sha256 "f89bb2ff39ee46444d2d33584e1e7a0443e33e08668f03765f83d796e94b3258"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.1/infisical_0.34.1_linux_armv6.tar.gz"
        sha256 "4a91f99030e9b437989afa66dd4a94e890a1ffd745a73552b37bb60475238757"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.1/infisical_0.34.1_linux_arm64.tar.gz"
        sha256 "92482deb771a1220808f9a3baee7821dc5a5b2dd22f03fee88b4d4770fc914ad"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
