# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04377 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.77"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.77/cli_0.43.77_darwin_amd64.tar.gz"
      sha256 "fae877a457c923a2f172cedc6672e8d052e513d2b7ee935476633bd22bd853cc"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.77/cli_0.43.77_darwin_arm64.tar.gz"
      sha256 "cb350c05bd2329bffa9371a5daa89635cd1dfe5ae84f63fb5d8b2317d4d68953"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.77/cli_0.43.77_linux_amd64.tar.gz"
        sha256 "a0d3fb50e998c29160f899c0ebcb60712755fbf60681bcfb10ae71b61b7bdea8"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.77/cli_0.43.77_linux_armv6.tar.gz"
        sha256 "700d7190aba3b84ca655dcc1129f1e3849fa22baaaf25484e7356633c76c440f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.77/cli_0.43.77_linux_arm64.tar.gz"
        sha256 "8c572cd50c0af3019eddfa8481b0e002b9036c38cb5fdd49ac13a4a57b1dcd1d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
