# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0401 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.40.1"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.1/infisical_0.40.1_darwin_amd64.tar.gz"
      sha256 "c15a203eb95a259de24e54905763a9583279c749b1729c869988dc59b13b40cb"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.1/infisical_0.40.1_darwin_arm64.tar.gz"
      sha256 "dff5262ee21d96e52b23c5d542a6018f0c704ede73af9b3327af6a7dd9c3583e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.1/infisical_0.40.1_linux_amd64.tar.gz"
        sha256 "2e0e130d5b96798063bf8d703a8320762b98f73048142a61fd46d84bbdfc2577"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.1/infisical_0.40.1_linux_armv6.tar.gz"
        sha256 "5cf3113f6ce661c6b89a8f24d4bd99449d7137a6609b3d1657a3994b0b888e62"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.40.1/infisical_0.40.1_linux_arm64.tar.gz"
        sha256 "8531a2b0527bf95d0e658166ded7c8a5b6f84cdcff8d018b7620cce559b8b76a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
