# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0285 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.28.5"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.5/infisical_0.28.5_darwin_amd64.tar.gz"
      sha256 "223c46565d53ad014dde27347408a77f3ce225e4757e249e5bc8c4f9a5c3e9c0"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.5/infisical_0.28.5_darwin_arm64.tar.gz"
      sha256 "9e4bfdaf90b3ce323b08a7d0fed0fe5091a80d1e8eb3b5ba6dcd1d7280221a11"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.5/infisical_0.28.5_linux_amd64.tar.gz"
        sha256 "8580c167a71350225377966ffe309754ba521927976ed0b4bb10238783488d5f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.5/infisical_0.28.5_linux_armv6.tar.gz"
        sha256 "e1c8af609d067254db976f2b2b3440df0207abeecaac4fc9ef97d2afb46e5cc3"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.5/infisical_0.28.5_linux_arm64.tar.gz"
        sha256 "e8a1701c54bc7597c6f2bacafbce415308c3fac353a98ff959586ed3212d27bd"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
