# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0168 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.16.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.8/infisical_0.16.8_darwin_arm64.tar.gz"
      sha256 "fb1d99565a1959c701a305673745f9be7374e4d03bedc4943d36f7a854a060cf"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.8/infisical_0.16.8_darwin_amd64.tar.gz"
      sha256 "17e48dc401084d3822d447bf4cc0ee331b4a36f2c9b8c28a8108f32b9a1c5fa2"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.8/infisical_0.16.8_linux_armv6.tar.gz"
      sha256 "5d10f401a43c98f147581c5df98c1ab3257f42e9758ba676129a00932a8fdccf"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.8/infisical_0.16.8_linux_amd64.tar.gz"
      sha256 "cea8bf3a458d2655e7361029ced380b0102d88724a66af1a517c77962770823e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.8/infisical_0.16.8_linux_arm64.tar.gz"
      sha256 "0ba7fa5809dfeee86415a69eeec811fe8ac749ebeba0728f7fbc9996c4654d17"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
