# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043107 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.107"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.107/cli_0.43.107_darwin_amd64.tar.gz"
    sha256 "cc04fdc07311d493890f97def658ed2730a0da12a8502c5b926436004b272beb"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.107/cli_0.43.107_darwin_arm64.tar.gz"
    sha256 "40753223452ed9538da069747485cbbdcfd858b791059265fd23641f553213ad"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
