# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04186 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.86"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.86/infisical_0.41.86_darwin_amd64.tar.gz"
      sha256 "9b87b5c6208d3dfacbcd38a9ca38ebd4d479827aa0af99e1244c962fa1799dc0"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.86/infisical_0.41.86_darwin_arm64.tar.gz"
      sha256 "e2fa8a4e52fffcaeb5a88f7f9742fc4b7c9df3a9c71eb0dca2988b760c865692"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.86/infisical_0.41.86_linux_amd64.tar.gz"
        sha256 "65b58e123a83c195e8c2b5e9ab42e1875855fdd57366622831ba3e5b1dadedfc"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.86/infisical_0.41.86_linux_armv6.tar.gz"
        sha256 "a5ccfe43321416682dd85794085203744dde6e1bed27295ed68676c7aacd2479"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.86/infisical_0.41.86_linux_arm64.tar.gz"
        sha256 "b9e8127fad14ca99026dab7034a464f8a7c5bb10c11d6ab366c1917a136ece47"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
