# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04325 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.25"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.25/cli_0.43.25_darwin_amd64.tar.gz"
      sha256 "d446ee66ad689cb1fadc6111850757710564f9b5c41ef18fa22065518f462d5a"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.25/cli_0.43.25_darwin_arm64.tar.gz"
      sha256 "90d283d672f1f724b61ff8fa236c8e9046a1a1478d83f9e4acefaca129ba8b35"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.25/cli_0.43.25_linux_amd64.tar.gz"
        sha256 "b5a4aa216e257c8129e5cd7d0fcbb5e5377b14fb5175c12060d43f01656d3ede"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.25/cli_0.43.25_linux_armv6.tar.gz"
        sha256 "7129b607f33f30ff6e7f18f7d0bd1e8e7f57592c38504b79976aa833521c1da7"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.25/cli_0.43.25_linux_arm64.tar.gz"
        sha256 "aedd890944e99c048bb8dd37e8433a4c48e9b9e6732645515ddd77bab32fdec9"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
