# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043104 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.104"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.104/cli_0.43.104_darwin_amd64.tar.gz"
    sha256 "2522c73cddbeb8106f0e9890e982c5a3f2fd7f7f6f126c2a4b6a8f793b2672fe"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.104/cli_0.43.104_darwin_arm64.tar.gz"
    sha256 "a52cfc3e6fd0d9232cd15c0c5fe7dcdab915db6dcf62ef46320a4a9bfe45c3d1"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
