# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043133 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.133"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.133/cli_0.43.133_darwin_amd64.tar.gz"
    sha256 "be82104dc0da65a71c8446700c4a31eba9cadd66409d6e4922dea835c02a783c"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.133/cli_0.43.133_darwin_arm64.tar.gz"
    sha256 "8fa6795b1d17578c108b9b63a5b4c74c38c5c8af604764f260a87082f7354f62"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
