# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0201 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.20.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.1/infisical_0.20.1_darwin_amd64.tar.gz"
      sha256 "b0518a521e2a923e44679344eb042a3b64c0987b8c1f8aa071d265c7ddb282bf"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.1/infisical_0.20.1_darwin_arm64.tar.gz"
      sha256 "20d35caab0b2e69c7dbf087ac8cd376da4a08f6b8780fadb2806ad1a5f384793"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.1/infisical_0.20.1_linux_amd64.tar.gz"
      sha256 "5b993fc462fa478a31f574128569763eaa6f6c9608a9e338431ddb1bee47a40a"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.1/infisical_0.20.1_linux_armv6.tar.gz"
      sha256 "de422e8b8ac26ae2dfbebdcdfed0e4967747b3779191c59cc7011a4c4bcc09e1"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.20.1/infisical_0.20.1_linux_arm64.tar.gz"
      sha256 "b7cd0db75617c267236a065168f8171f89bb0f9b0a8702f3f58717e9c380ad14"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
