# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04354 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.54"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.54/cli_0.43.54_darwin_amd64.tar.gz"
      sha256 "812dc8f1ac5fac8b7d9aa0c0e91007294a4049e66135056cc2886032e5f4cb96"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.54/cli_0.43.54_darwin_arm64.tar.gz"
      sha256 "054ee784da136f1999679e4a557e1097eba748adf62f7c9f3673dd59494f3e6f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.54/cli_0.43.54_linux_amd64.tar.gz"
        sha256 "6dccccb641f566870424c14744eed578d950a3bbfa03b045bb2548e7ec766d05"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.54/cli_0.43.54_linux_armv6.tar.gz"
        sha256 "04f6a5667cf5e5160060a7e0b1d53a9457c60a5afa74923dcbbe82fd9a918be0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.54/cli_0.43.54_linux_arm64.tar.gz"
        sha256 "77aa631a62e55185e7d2a04644cfec512d2c8987e9b3f925e9ea5287d9591444"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
