# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043112 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.112"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.112/cli_0.43.112_darwin_amd64.tar.gz"
    sha256 "52720c34f6c0495a0d80b2da3e76febc4dffde370b37363aeb0db269d79ad779"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.112/cli_0.43.112_darwin_arm64.tar.gz"
    sha256 "399ad3cd966c6148ebb46b15adeabc291f1a6c9dc2c97adb7fb6a2e7757a1c4b"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
