# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04380 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.80"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.80/cli_0.43.80_darwin_amd64.tar.gz"
    sha256 "bee4b3901f1567b1e5f8d9d85191a08ab3edfc1243a75611b1239687c81d54e0"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.80/cli_0.43.80_darwin_arm64.tar.gz"
    sha256 "148e3846adc400d0a0248d1b544b14a8aed0f91196818ef545ef9fc61f00c79e"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
