# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043126 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.126"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.126/cli_0.43.126_darwin_amd64.tar.gz"
    sha256 "b4b613a5632e5fe4a137b55407045c708b5a6709c64b68c41820d9cc5ba40274"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.126/cli_0.43.126_darwin_arm64.tar.gz"
    sha256 "95ee16c6768a849ec473dd6bfdf976cf855be9b98850e3899856c1bc669dacae"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
