# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0437 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.7"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.7/cli_0.43.7_darwin_amd64.tar.gz"
      sha256 "46876317a87034737db3647ae775d43eb23656b80cc6a1a9c03686b9fa200fa6"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.7/cli_0.43.7_darwin_arm64.tar.gz"
      sha256 "53eb3fce23d000c8ec962abf396649b8bfdb990fd3b5eaf6b14a9d7b779d7c94"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.7/cli_0.43.7_linux_amd64.tar.gz"
        sha256 "a36326fdb5c50f422955c65b7f535b464364dabd8e3baf7c7acf241f3dc6e186"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.7/cli_0.43.7_linux_armv6.tar.gz"
        sha256 "fe4928861103d4fdda1545843bfc6681109c69cad48238a60998d9407c0e8b3a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.7/cli_0.43.7_linux_arm64.tar.gz"
        sha256 "097202a6afd27296d0d746d35c17ce64752d85bff26d6e0ed865283337dbbcb6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
