# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04375 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.75"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.75/cli_0.43.75_darwin_amd64.tar.gz"
      sha256 "85cd55f9ca191149e9b70a1019a67e1835f173fe0c2c36ea5dc18165620de6a4"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.75/cli_0.43.75_darwin_arm64.tar.gz"
      sha256 "7115bbed8c85126ed3efa434104d83e620da8d7779e1816c5b31658ff2b090f5"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.75/cli_0.43.75_linux_amd64.tar.gz"
        sha256 "9ff987871b148ab409a691621a6bbaf1a090921c72c3032571378475c6bd850b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.75/cli_0.43.75_linux_armv6.tar.gz"
        sha256 "c8d71a0c14ea075828775f6569c2add9d9e9135ee4323087b4c10283532eaf47"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.75/cli_0.43.75_linux_arm64.tar.gz"
        sha256 "9535748c819da92fef3cc5b64b9af497611960f54da00ab9c0feb38ec89f0ff5"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
