# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04359 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.59"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.59/cli_0.43.59_darwin_amd64.tar.gz"
      sha256 "d7b9d2dcf0f4c70c6bfd0b1bc5a3720584b7895d80783a3e91121887cababdd5"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.59/cli_0.43.59_darwin_arm64.tar.gz"
      sha256 "9a88c375f6e6508232e118e6bd7f94d5666c62c042a62fe15b70443b94229f56"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.59/cli_0.43.59_linux_amd64.tar.gz"
        sha256 "144986a15e9b78ff6eb5125d04877f2f5bbdeacd63c124ab85ecfd3587f906fe"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.59/cli_0.43.59_linux_armv6.tar.gz"
        sha256 "7bbce1aeb4f00ec39226493bf79800d445a257630f27d8e98e2f01f28f9fda05"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.59/cli_0.43.59_linux_arm64.tar.gz"
        sha256 "31e7c54ece64d156714b78f12ee00d0d12a877fa931ae8a566132727f3df25b9"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
