# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043109 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.109"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.109/cli_0.43.109_darwin_amd64.tar.gz"
    sha256 "c70ad86bb1e4a2f57a217a9a74cb35d1ceea1d3dbc5b26554033e68153a882c4"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.109/cli_0.43.109_darwin_arm64.tar.gz"
    sha256 "b5cfe6320e884eece569b7a5c9908f4c0cbebe221d15af0ad158103050cd4611"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
