# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0166 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.16.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.6/infisical_0.16.6_darwin_arm64.tar.gz"
      sha256 "26f52029fc75d2afaf71fe463eaee35964637dcbfbb9962c0706b75770407abd"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.6/infisical_0.16.6_darwin_amd64.tar.gz"
      sha256 "b01b0c249dcafe73f54c46c0dae87ca9c74f9505cb7cf3fb2dc5cb74c31f4d47"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.6/infisical_0.16.6_linux_armv6.tar.gz"
      sha256 "f34a8c180dfc3a2e595ffee45ae73f8c422ed6ea081ba4548d76c3e6444bf988"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.6/infisical_0.16.6_linux_arm64.tar.gz"
      sha256 "694bc7f49f294b58078d5f9cfdb5c19a718269b23d663edd9c417e4894deae8f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.16.6/infisical_0.16.6_linux_amd64.tar.gz"
      sha256 "e567c2a57b095daeb88d41d3148e5d638f920856cc517e11bf669aae1621258d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
