# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infisical < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.73"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.73/cli_0.43.73_darwin_amd64.tar.gz"
      sha256 "54b346fe2ecc58b8860e8a93aa4437b324eef8ab0cc35d3528ad5ad688dde20f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.73/cli_0.43.73_darwin_arm64.tar.gz"
      sha256 "d780075754e0f0f0a753a25129d93f3704824f9d087358a9937e4a90ca393ecc"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.73/cli_0.43.73_linux_amd64.tar.gz"
        sha256 "44cdee1cf70bf0e93b224787be699a907abef052bd8c0aada28a59a83e49dd16"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.73/cli_0.43.73_linux_armv6.tar.gz"
        sha256 "b6734c2dfd368f1dfbe7a15b2182a4a8d4e25a1b7eaa4a98374dce66702f2681"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.73/cli_0.43.73_linux_arm64.tar.gz"
        sha256 "62741640279cc294ba6b509c079ec39df7db9a29b0c83f1cdd7de0cc0a4eec41"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
