# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04198 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.98"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.41.98/cli_0.41.98_darwin_amd64.tar.gz"
      sha256 "0909b5fe9df272b3e635c852d30541e913ec16ab779a486ca9413aa5af493d28"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.41.98/cli_0.41.98_darwin_arm64.tar.gz"
      sha256 "b8fcbb9d91f76fe392e41d9d3caa45983e46f2ae4398b12d501470e4cab4be28"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.98/cli_0.41.98_linux_amd64.tar.gz"
        sha256 "a59f999d129eb29ed1bbe295a4c78a63ace8b9396d1d496510f507ce7c97d865"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.98/cli_0.41.98_linux_armv6.tar.gz"
        sha256 "26f548ab76a3ee56941a0ff724ee4e3f4cdcd8423521f16e0743bf29a140c835"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.98/cli_0.41.98_linux_arm64.tar.gz"
        sha256 "4a0c858c5c85e500ed19a2ac7e247e14f673781bf8ee965e19f6b8c11a4ec765"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
