# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04319 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.19"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.19/cli_0.43.19_darwin_amd64.tar.gz"
      sha256 "0c152706306953cc39b009b67d17d5a5ebbe924858627ea88b038ca7acf3f827"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.19/cli_0.43.19_darwin_arm64.tar.gz"
      sha256 "78db4d3a4a97bc6d265cb5fc099e7b7d38285969559e591659accaa57ee153f3"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.19/cli_0.43.19_linux_amd64.tar.gz"
        sha256 "d32e24eea38d520549c4bfa9c8173c29309fa18db99d70da5d645a3d18baadfd"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.19/cli_0.43.19_linux_armv6.tar.gz"
        sha256 "c5caf7b90971446c62537db57726608685386effe7b890f313a8cd1d04ec577b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.19/cli_0.43.19_linux_arm64.tar.gz"
        sha256 "0d872d3cdcba74918612701fb7444b5ec11588107c7c0e71ea97ded2a9804aeb"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
