# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04383 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.83"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.83/cli_0.43.83_darwin_amd64.tar.gz"
    sha256 "92ee223a0b6e29318b5d76775026a47ca491402b5b7ddb0a3dc77680e6dda088"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.83/cli_0.43.83_darwin_arm64.tar.gz"
    sha256 "084aeb842a87245dae454feb771f4a926ccc4b838b3470a711badc8769ba99c9"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
