# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT03615 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.15"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.15/infisical_0.36.15_darwin_amd64.tar.gz"
      sha256 "e6cfbed22ff7bb5ee67601a26180afcead4ea239c3bbf16a1cc0c562e6bb228b"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.15/infisical_0.36.15_darwin_arm64.tar.gz"
      sha256 "08bab853eaaf66445d9d8bfd019c0b0ea031b1354c7347ded3d5166e7220c892"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.15/infisical_0.36.15_linux_amd64.tar.gz"
        sha256 "a502ebbe1264849ae9e88f56075959c7fd622a96d3039e69d89b51301a9682d4"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.15/infisical_0.36.15_linux_armv6.tar.gz"
        sha256 "2b77da79d13ebc8af98a9d05e12fdcb13c79896de06f547b007aad8bc5545a8b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.15/infisical_0.36.15_linux_arm64.tar.gz"
        sha256 "8c3d09214f5802929a84d998b69970f672d9eaf1680545f6bf9dec8a772399d4"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
