# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04342 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.42"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.42/cli_0.43.42_darwin_amd64.tar.gz"
      sha256 "f4d8a1759510a05c86eb32e72746e69f4a049f6cb9161fdd1d046d1958d24afc"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.42/cli_0.43.42_darwin_arm64.tar.gz"
      sha256 "be64ed3acd9a89f36d627f17014607939cdc5a44c052d96396d7a6a77fa62767"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.42/cli_0.43.42_linux_amd64.tar.gz"
        sha256 "344a71ccdbdfa6192bd8c901811dcd96a7a905048560de0473c6a15b003b8349"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.42/cli_0.43.42_linux_armv6.tar.gz"
        sha256 "1f9049b6e962a31d11d1371e142c228b8a977ef0ed66d970bc3d3497c0a39cbe"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.42/cli_0.43.42_linux_arm64.tar.gz"
        sha256 "9451edf334cda9d06e78405e6d673d07693be36217ea79655bd7c199142ccd8a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
