# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04372 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.72"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.72/cli_0.43.72_darwin_amd64.tar.gz"
      sha256 "1fbe6cf3c6ee3515c7ea4a6915a14c5130c29c83e916cefbc701d35c381bcf22"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.72/cli_0.43.72_darwin_arm64.tar.gz"
      sha256 "2abd8fdf2709d3b37023c1830c406efe844b09e3df080f0839fd0116320d5f0d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.72/cli_0.43.72_linux_amd64.tar.gz"
        sha256 "28a1e4f504062e9577b6987d4572ad7bdcc78b8c5a48a77fa958100c0c311460"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.72/cli_0.43.72_linux_armv6.tar.gz"
        sha256 "39489c1dacead520893f0b79d1dda45147d15da2af5c8d2a874a52baf79c2c1a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.72/cli_0.43.72_linux_arm64.tar.gz"
        sha256 "b486c1f6dcb0317cc4dc42260f7820b7801b7a34ad6c12085a0fdc82b9ac7f4f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
