# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043139 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.139"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.139/cli_0.43.139_darwin_amd64.tar.gz"
    sha256 "2793368fb8759b47ef55f17145d22ebaa53fbd751beb4fdb5a6b51dfcf261e64"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.139/cli_0.43.139_darwin_arm64.tar.gz"
    sha256 "bf5d311b1cac5f3969c44949a32d026df9be42b5b1a454fd0e4061a3b23fa219"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
