# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0430 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_darwin_amd64.tar.gz"
      sha256 "afbca26444c0e7d92382c3ab5ce119655b6069f579f06eb190289cb3320403c9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_darwin_arm64.tar.gz"
      sha256 "543415ecfb279c14a941d603337971ab658e82a9a1c7ce0fa10ab4d4d35f17be"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_linux_amd64.tar.gz"
        sha256 "ddfef4fc37fb9b7f589628562e2f0f25455e5f1e30a927ace956b0e80650f9fa"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_linux_armv6.tar.gz"
        sha256 "be53acd4d6fbf23d6b1e55cc0efb52c5d92a8f56f2bf164c1ed23951bbd85e11"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_linux_arm64.tar.gz"
        sha256 "2296c0bed0d4d053800b57b3f5349091c959e278583f8e90c58ae666cc182703"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
