# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04318 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.18"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.18/cli_0.43.18_darwin_amd64.tar.gz"
      sha256 "d33fcb22c06dcfde5f36f7dc38710c888821a7316ece9c9924e2802f0a4d5eca"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.18/cli_0.43.18_darwin_arm64.tar.gz"
      sha256 "5137f3968e42631091fed73aa66271e0f374c6fb940fec96a377ca197c0371e1"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.18/cli_0.43.18_linux_amd64.tar.gz"
        sha256 "d8de19fcfd60640803d9f165f32c28fc5283b10eaa252b29382b8b56231b2594"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.18/cli_0.43.18_linux_armv6.tar.gz"
        sha256 "bf824fe6c17255f50886a934db8339124634f83094a4449007be65a922e07def"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.18/cli_0.43.18_linux_arm64.tar.gz"
        sha256 "f47491be1854fb426d965d226a689d2da50ff5483b8c9abe18334c11f4382551"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
