# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043120 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.120"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.120/cli_0.43.120_darwin_amd64.tar.gz"
    sha256 "98290694f640b33a6f535a4882ceaa97523f66e32b00b0428a0ad6760ad2bdcf"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.120/cli_0.43.120_darwin_arm64.tar.gz"
    sha256 "6baaefd374f3c45c1b34795fde88a9cb94809429b91b4f4fda3aaf5e27dd0432"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
