# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0175 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.17.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.17.5/infisical_0.17.5_darwin_amd64.tar.gz"
      sha256 "204e8c3db435d5abbb6a80a76656809a01a9c3cca5d321d63f0acd9e7df5346f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.17.5/infisical_0.17.5_darwin_arm64.tar.gz"
      sha256 "8bfcaf4365d499b2ec9cfb00e61b158a4f107c74abe3941f93ae3118a7e0c4a1"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.17.5/infisical_0.17.5_linux_armv6.tar.gz"
      sha256 "cd724ca4309ff2de45a0bcb08876b60a99143579d013e37233247800c7eb7225"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.17.5/infisical_0.17.5_linux_arm64.tar.gz"
      sha256 "43af4ec4fe56f19b2692ab9a81203abcb9977b4f3f9bdb46b3aeda38d417e1d8"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.17.5/infisical_0.17.5_linux_amd64.tar.gz"
      sha256 "55a6dafff36a3b0dd123b18fb56ab81c2f81f235ebcbfee9c4fc8939070eadaa"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
