# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04355 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.55"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.55/cli_0.43.55_darwin_amd64.tar.gz"
      sha256 "b1d7e6521141e5381c2bc338d20f93bcd05ca72abaccd674e1b3486efed7183d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.55/cli_0.43.55_darwin_arm64.tar.gz"
      sha256 "ee3d72fe04f38e191a6c4c1843ac202c4efbeaa4dd4343695e47acfde339e20e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.55/cli_0.43.55_linux_amd64.tar.gz"
        sha256 "13ef9832543a3490e2e6f574e444b9b4c400e90fc49332e6553c83b22b14eec0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.55/cli_0.43.55_linux_armv6.tar.gz"
        sha256 "228b76a4197d579fbd1ff5597de5a5f7b6bef67e4fa244ccd8136b0e744a20d6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.55/cli_0.43.55_linux_arm64.tar.gz"
        sha256 "6b2fa45da2258d6e302bda3101b58029fbefa25011789d10e545496bb9b78ff6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
