# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0232 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.23.2"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.2/infisical_0.23.2_darwin_amd64.tar.gz"
      sha256 "5ba1457dcd6f4fb381c71318ae562984969daa6e14a63d83b657e7c8546d7a84"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.2/infisical_0.23.2_darwin_arm64.tar.gz"
      sha256 "79e754df3e198bc43aef13377808627328a4cd9f68dd586a8401cf5ce5d75351"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.2/infisical_0.23.2_linux_amd64.tar.gz"
        sha256 "82f02c219799c2a8ca9dfc956728a473765b0b3e66dab84efd27c221aa708dca"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.2/infisical_0.23.2_linux_armv6.tar.gz"
        sha256 "7bfe49d7677443a6398f60a840360d56b1e82fa9f00c48e25aecc9994d19c056"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.2/infisical_0.23.2_linux_arm64.tar.gz"
        sha256 "9f2409c324e3862019efb4e962958371e053d5f7649cb33afea8dc3c6cfdb4da"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
