# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0290 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.29.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.29.0/infisical_0.29.0_darwin_amd64.tar.gz"
      sha256 "b7bb378e687ba2c92f92fdf27587935d6dd9dfe80c652ab078b2aecbff49ab30"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.29.0/infisical_0.29.0_darwin_arm64.tar.gz"
      sha256 "6bcb273ef8c79187d3e2c93c20f8a7af8796b639e23825a7234c281bbd5273a4"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.29.0/infisical_0.29.0_linux_amd64.tar.gz"
        sha256 "ce8b34d23c5a8f0b32464f7a64537901bbcd27764a53e71f825e13c9d199c18d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.29.0/infisical_0.29.0_linux_armv6.tar.gz"
        sha256 "dd3cc2bce766a19c0ad75a6e60e5a03a3fa6b100f87be116b96be01bd092a920"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.29.0/infisical_0.29.0_linux_arm64.tar.gz"
        sha256 "7256bed3751da6ced157722b4fbafabc48b7046bc0dcfca51728851be4ff1b35"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
