# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043127 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.127"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.127/cli_0.43.127_darwin_amd64.tar.gz"
    sha256 "d2f0941cf93f812e33791197142e61550ba65ffceaaa67e14e7fc8bec8fee18e"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.127/cli_0.43.127_darwin_arm64.tar.gz"
    sha256 "abb867f7feb981aa863db77d98857f1809eb5c5def115097375b44d77ad453bc"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
