# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0331 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.33.1"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.33.1/infisical_0.33.1_darwin_amd64.tar.gz"
      sha256 "94cefab0e1fd748869e2dc526c6542aa34c00f678b238bb45f681137fe344336"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.33.1/infisical_0.33.1_darwin_arm64.tar.gz"
      sha256 "aba72d1e5806e4c7cbc4483ee5c3de8fb68ba610a01f397538a86ed2a0862f79"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.33.1/infisical_0.33.1_linux_amd64.tar.gz"
        sha256 "3dae139bcac7958cfabb9ff12e01e5545a0b00132eb262a0336b2c26fe634e1e"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.33.1/infisical_0.33.1_linux_armv6.tar.gz"
        sha256 "0c046780da83cb2625ddc3df753f6fe17360c1c2229ef00cbcd972e1851da627"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.33.1/infisical_0.33.1_linux_arm64.tar.gz"
        sha256 "b3f5f07233f3423acb0f80f69b43e4cdc551a71713458e0c0c1f689682a93faf"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
