# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043105 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.105"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.105/cli_0.43.105_darwin_amd64.tar.gz"
    sha256 "76150c511f32a34f71cdba249d5107ae1deec07e81178575bcf3da4f9a2806b8"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.105/cli_0.43.105_darwin_arm64.tar.gz"
    sha256 "05c39bcc05fdc44e5906dc65635675fab00d9f50b0f45d0e35a3386ffde03520"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
