# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04362 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.62"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.62/cli_0.43.62_darwin_amd64.tar.gz"
      sha256 "a0213990157415066e2b5bb6d7f643125aa27fe9580e2bc3544bd6e7a638b2c8"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.62/cli_0.43.62_darwin_arm64.tar.gz"
      sha256 "ec9f4b543c8828c3f8dc6390e9bb7db47ae200281d19bd98ecb5fa5b9116811c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.62/cli_0.43.62_linux_amd64.tar.gz"
        sha256 "2cd24369d77a30c0af803175d1328ef54e98fe8b8f7aca18c1e05c1a54dbb836"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.62/cli_0.43.62_linux_armv6.tar.gz"
        sha256 "e3abc7436871f3dd92522f1c1d733c8c41b113e2d907e9d5e3922030416f8a99"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.62/cli_0.43.62_linux_arm64.tar.gz"
        sha256 "ae56f11e472bdb53611bb874907e1ea4291b906f67981a2d30d197a12f8b6540"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
