# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04351 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.51"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.51/cli_0.43.51_darwin_amd64.tar.gz"
      sha256 "c909668c7de2fec6184c53395497b9c7b02be821e73816b45c47d7b45988ff02"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.51/cli_0.43.51_darwin_arm64.tar.gz"
      sha256 "ce3bfbaaf696401869b960ba8cefa9b800a559dc44f61bb49d833af0b78326be"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.51/cli_0.43.51_linux_amd64.tar.gz"
        sha256 "5a8743eda2641019809f87454798f515755ffbf6e44ac716f6612e3c055669ff"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.51/cli_0.43.51_linux_armv6.tar.gz"
        sha256 "b7a38580850ec560068a6c7ddee73dc11e20f1187acaf2d56cf7cbb55c9db9a4"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.51/cli_0.43.51_linux_arm64.tar.gz"
        sha256 "7714db8f5fd6f7fe6f8ae8ae7d6263a9ab197abe848c9d9a98a9062954e313f8"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
