# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043118 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.118"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.118/cli_0.43.118_darwin_amd64.tar.gz"
    sha256 "f8a3247ceafe9a51c64fe0de2853bfc0d5170115e9251ff6b1b8c13963ba588a"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.118/cli_0.43.118_darwin_arm64.tar.gz"
    sha256 "10132777121cdfce1aaec267a3a1aeb70940db65d582776dbff195bc5c86a487"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
