# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04356 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.56"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.56/cli_0.43.56_darwin_amd64.tar.gz"
      sha256 "f2dd97cfc103fca0135895842dc4bd71b7506410f82c44a8113ff5cfb2f8b40e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.56/cli_0.43.56_darwin_arm64.tar.gz"
      sha256 "d73b5a7ec8ed21e39e193f35d0bc5feda5f9d69df49cb4a8b5080c60dbbc8044"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.56/cli_0.43.56_linux_amd64.tar.gz"
        sha256 "1b6c4fbd1ff999a4c63a4d5f139a803aeb428e7b3f1ced0bd8d326f91c013b24"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.56/cli_0.43.56_linux_armv6.tar.gz"
        sha256 "a25f5b23bbad8c48662bd46552152f5f681c434406a10113fa37ca79584ef4b3"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.56/cli_0.43.56_linux_arm64.tar.gz"
        sha256 "ba182b8357caa3c96f6f522c1f3486fcd2a61f59adf7aa9936da6356c27db1ee"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
