# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0262 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.26.2"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.26.2/infisical_0.26.2_darwin_amd64.tar.gz"
      sha256 "a7570287635fa1d40feaf9a2559bb3ea7bea922330e5bb2eb22b80be6c5baca0"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.26.2/infisical_0.26.2_darwin_arm64.tar.gz"
      sha256 "05b829d9e23270c927df0a736da116651e7ffa816cb3ab14811ad2ea7c2dace2"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.26.2/infisical_0.26.2_linux_amd64.tar.gz"
        sha256 "82f076c76a2e07e7e152659b8b5288b5c6b292402cba9e1ffc9d17b67469c0b1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.26.2/infisical_0.26.2_linux_armv6.tar.gz"
        sha256 "e85b548fa9449739416a703030dfacef3c620510b65518dd236abde21a42621a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.26.2/infisical_0.26.2_linux_arm64.tar.gz"
        sha256 "a4ac678065fcbe53cbef13988df8bdbc0d6e568251094f5da62b8231d7db10de"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
