# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04363 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.63"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.63/cli_0.43.63_darwin_amd64.tar.gz"
      sha256 "08a8f758e60d0f012b5e9790e8207021ab0f2639b2871afa0ed4032502d52cf0"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.63/cli_0.43.63_darwin_arm64.tar.gz"
      sha256 "b09e9a54f6b1cf2af9f028202e01646b4c333b42fdb0e670f0f63e7dadc9251e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.63/cli_0.43.63_linux_amd64.tar.gz"
        sha256 "ad34545e1d7cc200b3c32d3e8713e663bacb31b1e2ee472d9813b5a9a123ea37"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.63/cli_0.43.63_linux_armv6.tar.gz"
        sha256 "daec5563fe865f96aa9122a0f1cc44898c9fa20d5022644a9250c44381f7a345"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.63/cli_0.43.63_linux_arm64.tar.gz"
        sha256 "8c09e54dd34fcade3b9e6bb7adf0567b396e8b638e029e45a4827edac3d7292c"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
