# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0318 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.31.8"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.8/infisical_0.31.8_darwin_amd64.tar.gz"
      sha256 "87a56823e5dded90e254452a48c44c22973b7fdb3f1d98a57f0cd71603d6015f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.8/infisical_0.31.8_darwin_arm64.tar.gz"
      sha256 "a37f6e1d97753236c4b33a43c0801b8544bfc3c2c4891555bc98da5fe4909b0c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.8/infisical_0.31.8_linux_amd64.tar.gz"
        sha256 "4a459c4676e6bca5855f476f01f8fbd6e1cd45b559d0b60bcf23e882249a327c"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.8/infisical_0.31.8_linux_armv6.tar.gz"
        sha256 "f499ec96300bbc7ab9281bc5aedddf5829e04f79092eaad47fc618eabc78c7f9"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.8/infisical_0.31.8_linux_arm64.tar.gz"
        sha256 "ed35ae35382b71c4a7eb7e2a8dee3a02e496afd7e0eb396b4e9cf8881f6dcc4d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
