# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04346 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.46"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.46/cli_0.43.46_darwin_amd64.tar.gz"
      sha256 "86d3af7c89fd043e204ebca375438898b5dbb0479babd6fddcc44a8fea7d03e5"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.46/cli_0.43.46_darwin_arm64.tar.gz"
      sha256 "3a8a9238341e68b23678371ed92a1f1b814e2f4840ae8383655286b7e2a756a4"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.46/cli_0.43.46_linux_amd64.tar.gz"
        sha256 "3457a1f9fa51f1b04bb759bd60fd5ee77dc51509ac4058248cb8c68b1b1372ff"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.46/cli_0.43.46_linux_armv6.tar.gz"
        sha256 "1da2bfa4064ef19f85eee8a87010de152210b23726343a4ce243ea4537ff04c1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.46/cli_0.43.46_linux_arm64.tar.gz"
        sha256 "89bd57b8ed9934c421565397bb8fdaf4906b61bae2b6d8b68eca2af01393b605"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
