# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043116 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.116"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.116/cli_0.43.116_darwin_amd64.tar.gz"
    sha256 "ffc518c780f798909f47718b0353eff2213381dfde566b4d96f40d34acde82c1"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.116/cli_0.43.116_darwin_arm64.tar.gz"
    sha256 "8d1612f5bf7ecaa27ab8d295760c7f6b7267ad4227df1ccde71d75ae34c36540"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
