# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04321 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.21"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.21/cli_0.43.21_darwin_amd64.tar.gz"
      sha256 "b3d60bd0f2aa9f46d380fd1eaece752cf58e0b7b5d028c32381ea2c436bfdd7d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.21/cli_0.43.21_darwin_arm64.tar.gz"
      sha256 "9f7a9501d8abbfb2f65ae7c953db98424ec494bc78b0924af5dc531bd8149c31"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.21/cli_0.43.21_linux_amd64.tar.gz"
        sha256 "789e17ed14f6b5d99ee3dca2971c0472aadec6588b16faaac1373809e975ebd6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.21/cli_0.43.21_linux_armv6.tar.gz"
        sha256 "d4317cac2593bf09cd3bc9c9a9181e42b7941e6e6a5dede9aa78993d37febb74"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.21/cli_0.43.21_linux_arm64.tar.gz"
        sha256 "404a7797d261279a34c15ab84e2ffefdcaed421882f537d4eda77a96f5035911"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
