# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04181 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.81"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.81/infisical_0.41.81_darwin_amd64.tar.gz"
      sha256 "d8f88617dc7d12b8dd6aee81599f049d8d8d379915089bb043ae9a3b5883a93c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.81/infisical_0.41.81_darwin_arm64.tar.gz"
      sha256 "a7e137496d3147be5b15a71df413bf9931aaaa823269b818da3039364a30fa5e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.81/infisical_0.41.81_linux_amd64.tar.gz"
        sha256 "fc921ed1b29202aa89d232ab0756e2ba6b4a5593ea10b8cc7eff068c7c5843d2"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.81/infisical_0.41.81_linux_armv6.tar.gz"
        sha256 "898959e46ee697d76239e5310d5cf91c05625056dfe0f01e00cc724e66c180fb"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.81/infisical_0.41.81_linux_arm64.tar.gz"
        sha256 "c98eef01717d3d746826ebc1b8622a4e3cc0997c0c6043ebe2944440813a2b56"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
