# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0220 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.22.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.0/infisical_0.22.0_darwin_amd64.tar.gz"
      sha256 "d29114f96a994b97075c514191035a3045a3efe1c63bb06188545d4ca1f6dd97"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.0/infisical_0.22.0_darwin_arm64.tar.gz"
      sha256 "73b131b4d7ca4097cd21725caf7994c1458b5f162048ff99f1e30762f464c70e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.0/infisical_0.22.0_linux_amd64.tar.gz"
      sha256 "17f308da1b0f6162efcd65fa23b7ccb47d5545525b09405a9649299d843cb2a9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.0/infisical_0.22.0_linux_armv6.tar.gz"
      sha256 "655dee8606e3bca1e8fbcb9a93cc153fe9c72f4341861fe17cc7db6eadf56c6d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.22.0/infisical_0.22.0_linux_arm64.tar.gz"
      sha256 "0334ee68e1dc0d702cee3c730bff73c5bffc885a0513662ffc4e7b2dc913eec0"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
