# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0181 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.18.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.1/infisical_0.18.1_darwin_amd64.tar.gz"
      sha256 "3815feefb801c3113234d3d2bea49b44ca7ac406518c68a34de2252e6befbf10"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.1/infisical_0.18.1_darwin_arm64.tar.gz"
      sha256 "061948dd4b7155422a66411f16697852cfdfbc71c0df400fcf0df14fe51d5738"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.1/infisical_0.18.1_linux_amd64.tar.gz"
      sha256 "5ca478ade2140a0662d7e6621c00519983f906e55122f3aa736c6e233cb76322"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.1/infisical_0.18.1_linux_armv6.tar.gz"
      sha256 "e0e6cc25ea311c922cf00cd8abb4cbae89d96ad68e182d16f1497ea1c8e31b00"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.18.1/infisical_0.18.1_linux_arm64.tar.gz"
      sha256 "a82538ac92f2cb164ffe0cb727e45928b80acbf6c21574c63f66b14553b2221b"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
