# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04343 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.43"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.43/cli_0.43.43_darwin_amd64.tar.gz"
      sha256 "8c72adad423c081f65f69889b3ab2caa3ea897853ad53a745e517fa14825a33d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.43/cli_0.43.43_darwin_arm64.tar.gz"
      sha256 "97cbb9ccf56ff03133351ee64b9c45299f90e4781e1cf48fcf4b44050b0c189f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.43/cli_0.43.43_linux_amd64.tar.gz"
        sha256 "ea4bfa270f031c76446412b6cc344d5e0771c7a3bb7c6bbda3a177e9beaca983"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.43/cli_0.43.43_linux_armv6.tar.gz"
        sha256 "c53e8dc47c35c097e63471b4379eadbbcf160c274209bd29df5dbc4f229ff487"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.43/cli_0.43.43_linux_arm64.tar.gz"
        sha256 "6a0356d213fc3db0323e76f75222b89f32eeae9401736caa5e82a7f0afce7c04"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
