# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043100 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.100"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.100/cli_0.43.100_darwin_amd64.tar.gz"
    sha256 "be896eb91e8b69ee2bd08f364b06bd54c2fc3e63a7843a6756cc60e8e171f9de"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.100/cli_0.43.100_darwin_arm64.tar.gz"
    sha256 "eb94660faa7d6ea9124c3e9a74dbd6268fd21edd26d1431abba51219ca4ae059"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
