# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043122 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.122"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.122/cli_0.43.122_darwin_amd64.tar.gz"
    sha256 "bf47f1a83decf901d2069d4ff23a20ed331bc6e999b7226c160d8a749b78bb1b"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.122/cli_0.43.122_darwin_arm64.tar.gz"
    sha256 "89d71aa45377cbc3fa7f82645e60792a4398a3d3a020ac13b7877ff0661625eb"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
