# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04184 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.84"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.84/infisical_0.41.84_darwin_amd64.tar.gz"
      sha256 "1162761d33118590c1dd62f260a808ef5a18bcd1c44d72fc8ad43ec84a02b8db"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.84/infisical_0.41.84_darwin_arm64.tar.gz"
      sha256 "a76bd291126059028eb2fbafdaac192262771c8b0a3048600292cb1c1c6d186e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.84/infisical_0.41.84_linux_amd64.tar.gz"
        sha256 "7d5ded874561596307ec076b60de1b70bf6916699d384b2acb9f5eef4cbe8c85"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.84/infisical_0.41.84_linux_armv6.tar.gz"
        sha256 "5c249ca043e5ffc74487834d8193922f09395f9227304a1ab01d61b502e6f7d9"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.41.84/infisical_0.41.84_linux_arm64.tar.gz"
        sha256 "dcf7beacb4a3a533ffdce2c52aac7b3df0f2be99ac444333727b8b41a34a8968"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
