# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04197 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.97"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.41.97/cli_0.41.97_darwin_amd64.tar.gz"
      sha256 "d35632bd60b6d53966a21969cff0a135a915db7d603a89a6f5d0732c5451c919"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.41.97/cli_0.41.97_darwin_arm64.tar.gz"
      sha256 "69bbe24c696dc4eb3c69e5a0cd93f8fea94afa157758a1c390e041d55577be53"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.97/cli_0.41.97_linux_amd64.tar.gz"
        sha256 "c8acb83f28a2b524cddf3b4e6872ed18dad12a7b2bff2115a23a049dcd3a1da6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.97/cli_0.41.97_linux_armv6.tar.gz"
        sha256 "f0e0d89ddc5233c3d994bcb07ad8e58fe218a4e052ac47a191a9099ccb3d91e5"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.97/cli_0.41.97_linux_arm64.tar.gz"
        sha256 "ef9ba168f4ae39f2c5b60e57d89acc7241d808c91098f29d223698479952fda2"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
