# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0151 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.15.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.15.1/infisical_0.15.1_darwin_arm64.tar.gz"
      sha256 "1cfa25db16aaf6395dffb818aab703eb91a9feaebdf2ba6eb7748fc86b89fd97"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.15.1/infisical_0.15.1_darwin_amd64.tar.gz"
      sha256 "a6b6c2d85b25d0f974c7f5544630a2eeba960832cc06b9af91660da302176d4d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.15.1/infisical_0.15.1_linux_arm64.tar.gz"
      sha256 "7f752c1b2f48ac0f5d1442a6fc6830c674972cb2bda642444bf16a11b0019a42"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.15.1/infisical_0.15.1_linux_armv6.tar.gz"
      sha256 "5913e5e07f7b2ea1aacad1ea245cc9c90766f64037939772ee8304833f490666"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.15.1/infisical_0.15.1_linux_amd64.tar.gz"
      sha256 "59f77c9649210a1cbad8e9e67a98fa5eea5b1465b4868570a469dc784a224ee1"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
