# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04322 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.22"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.22/cli_0.43.22_darwin_amd64.tar.gz"
      sha256 "70c7f47c74b272f26900148f738bb7fae339ca0bd198ef98dbbdec520f4625ad"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.22/cli_0.43.22_darwin_arm64.tar.gz"
      sha256 "ac641894661ffafbff9802faea1a58d8b471f425b11bae688f05ce728daf0b05"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.22/cli_0.43.22_linux_amd64.tar.gz"
        sha256 "33ac01f422b26330f68f540f697f317bee577c4a843618c297f7b45784047fb1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.22/cli_0.43.22_linux_armv6.tar.gz"
        sha256 "d7ce340d62fe775132fa68e22433259bd42fb3eec8b58f3377a12c4ac1375edb"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.22/cli_0.43.22_linux_arm64.tar.gz"
        sha256 "ea44084e3b366b4a68619ee4531ce851fb54133fa8273a1cceb4e2051c87d99f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
