# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04326 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.26"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.26/cli_0.43.26_darwin_amd64.tar.gz"
      sha256 "6341cd49bd7c7524c6b16986f33e0a5d1019883ee338d79dc5e05493aa4a1516"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.26/cli_0.43.26_darwin_arm64.tar.gz"
      sha256 "2ab702775a80223de7b095bbdc54c3d69788a6f01778f90fe74bf13cad876472"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.26/cli_0.43.26_linux_amd64.tar.gz"
        sha256 "f4b0be3e2bb0da738edf343ec4a9f93f9c6b824e41abcf84efafaa9f6eaf123a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.26/cli_0.43.26_linux_armv6.tar.gz"
        sha256 "4bd8a513f240c3384805bd412ccbda316a7528a7510204aaa1c65e8c86ebb08a"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.26/cli_0.43.26_linux_arm64.tar.gz"
        sha256 "d47de300ca395ecfebe5e6390aa66ca5acedb95bce1d656c60c10d751e5ae9d0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
