# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043125 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.125"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.125/cli_0.43.125_darwin_amd64.tar.gz"
    sha256 "2bda04d930fa1213d59968e93fbe53b62b0a3344d45bc373fb3230dfc840cd73"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.125/cli_0.43.125_darwin_arm64.tar.gz"
    sha256 "253ab2f1aad9bf9e91c751192118a9d6f012f2af17185b41be34c3884c432b37"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
