# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0231 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.23.1"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.1/infisical_0.23.1_darwin_amd64.tar.gz"
      sha256 "69ab3d3ed90780b58f02b6c9c8c16703701e53fa05a6794bcff0ad2582d25d2a"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.1/infisical_0.23.1_darwin_arm64.tar.gz"
      sha256 "a11b3f80d04397b5d0db42d6df9034ab9cb842cc30c4550cefb639713c63f731"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.1/infisical_0.23.1_linux_amd64.tar.gz"
        sha256 "a2cb7e8aa697d691278b9770914644b1bd2b7cbdebfa20392d97c19d2fa52a51"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.1/infisical_0.23.1_linux_armv6.tar.gz"
        sha256 "c7ccbeaa5c46c78ca2ccb027d49c74e22b977b4bd60aae101a0916c95068ede2"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.1/infisical_0.23.1_linux_arm64.tar.gz"
        sha256 "d0d76c77086bc9d3c0f35a991461786c765f74dad34f374a8635221a4f72ea8d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
