# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0314 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.31.4"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.4/infisical_0.31.4_darwin_amd64.tar.gz"
      sha256 "f6c78102341744225f475d78dfb3d1638b500a6e3d5e73e658d83e82f44efe5c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.4/infisical_0.31.4_darwin_arm64.tar.gz"
      sha256 "04dbf11e906de030925c50914847c9c6f7daba65470a26de38ab1de8daf32272"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.4/infisical_0.31.4_linux_amd64.tar.gz"
        sha256 "47e106941053c119939fa894920af396e0d92ed66adf7ea8eaf1a06a0a4b0e1e"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.4/infisical_0.31.4_linux_armv6.tar.gz"
        sha256 "ec9c03a140e5f4f724e67148c2a3c8c0f6c820f37e6dde17c6a29b79b0dab187"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.31.4/infisical_0.31.4_linux_arm64.tar.gz"
        sha256 "2f3d886e6a06da2a23b32d0ec7683e6630791c0963aeaf6a9d3e5649e6c31afb"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
