# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0432 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.2"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.2/cli_0.43.2_darwin_amd64.tar.gz"
      sha256 "b0ac2b72e4b93ebb7c633e5368af6589aabac9f7590b6fb2cc3bf33021e79d45"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.2/cli_0.43.2_darwin_arm64.tar.gz"
      sha256 "7ad5305f3196c6700bcebfdacb6911467c5a0fa4f03f778e0015012063b35583"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.2/cli_0.43.2_linux_amd64.tar.gz"
        sha256 "b520dc6dc9e7a7022e9deec03ea73479b6754e1ad29cec26efe013562e78887d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.2/cli_0.43.2_linux_armv6.tar.gz"
        sha256 "8bee6a3f222db300a43c472ad4748887070cad2b7024d0559824fed965ad0677"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.2/cli_0.43.2_linux_arm64.tar.gz"
        sha256 "d85504afaa8b4c66d345eee4e64e9a433d37aa4c474b1e8f02d50ffaa9ac04d2"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
