# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0270 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.27.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.27.0/infisical_0.27.0_darwin_amd64.tar.gz"
      sha256 "5eba74e47782472b0f4a8dcc205702225d54fb44d5c01f4901f01bf2ae1db791"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.27.0/infisical_0.27.0_darwin_arm64.tar.gz"
      sha256 "b97840e356dd0ab81e80e041e5806369351bc1b9b5b8a345f6829fad0bbcc3de"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.27.0/infisical_0.27.0_linux_amd64.tar.gz"
        sha256 "33f2d8ab75b6d345376028ca0d03a544a68a6627e5bcbff68ccf46d5bae1ef6d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.27.0/infisical_0.27.0_linux_armv6.tar.gz"
        sha256 "c9928d938446308ff3b3425b51b6d1957b051c809ff3b6e1361e3f1b30063e2c"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.27.0/infisical_0.27.0_linux_arm64.tar.gz"
        sha256 "84a47b09e996aaa88f0e9ebbe64f029500330ba488f415c00c288581ed8bce65"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
