# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0286 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.28.6"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.6/infisical_0.28.6_darwin_amd64.tar.gz"
      sha256 "8f47f83612e2bc6f8c9b38ad3929c071cfc44008855449f8e30dd43272c29156"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.6/infisical_0.28.6_darwin_arm64.tar.gz"
      sha256 "b3a6e600d62eb803aaf79f51fa58a94e1737f6acaac30db421267deb98569167"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.6/infisical_0.28.6_linux_amd64.tar.gz"
        sha256 "8b3554c3f45c1fe53a8b990274f1a88ec045f8e9ede34401624e2c256fc12ce0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.6/infisical_0.28.6_linux_armv6.tar.gz"
        sha256 "5d48976774e3c2bbe0d7c3b8f270ba72fb5b743dceb9677922d7f7725fb33269"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.28.6/infisical_0.28.6_linux_arm64.tar.gz"
        sha256 "86e9d1038db120c72ee4906d4e789b59728410221e0481f2781c159ce191db95"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
