# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04386 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.86"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.86/cli_0.43.86_darwin_amd64.tar.gz"
    sha256 "a53e4c36e38ead48716273290f295e93bc655a904f03468075d27bbd965ab1d6"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.86/cli_0.43.86_darwin_arm64.tar.gz"
    sha256 "8f79bb3f714138db56d3ef15ce2ac206aac55d52edb7876d2b871c4ac9e43336"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
