# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043141 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.141"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.141/cli_0.43.141_darwin_amd64.tar.gz"
    sha256 "d8222cca518ce02da42b6cc6be3448eecec9e0347cfe39cab2f8ef842fcacb82"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.141/cli_0.43.141_darwin_arm64.tar.gz"
    sha256 "868aae3e772f3f0f17c2d5518c4ce9232920954279d3ccaba8174e65bffe49d5"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
