# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04393 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.93"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.93/cli_0.43.93_darwin_amd64.tar.gz"
    sha256 "8ad33d379bcd23fc77f7fca9c17481f2935a2190a095c600fb2fe9a395249ec1"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.93/cli_0.43.93_darwin_arm64.tar.gz"
    sha256 "9322d732a60fd651260c2216e68b655a306e935aa023a8fd121d09bc83c1b811"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
