# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0233 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.23.3"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.3/infisical_0.23.3_darwin_amd64.tar.gz"
      sha256 "a8b8d911de778e5482aa8c40d010de0f3fe435751089cf5403719a2f121591b3"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.3/infisical_0.23.3_darwin_arm64.tar.gz"
      sha256 "9f829a0cf94b763c1e4511dda8df0dda11ab02ab2a6328960ffdf1a637e0624e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.3/infisical_0.23.3_linux_amd64.tar.gz"
        sha256 "2febae28eea82168c45ca90e0b238dfb45478b32e969e3deee9e8bc98fe6b6ce"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.3/infisical_0.23.3_linux_armv6.tar.gz"
        sha256 "4688037a87ad08527f848a0d577ab2ee94c753e9b372bebfcea4ce5cc5a58f3c"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.23.3/infisical_0.23.3_linux_arm64.tar.gz"
        sha256 "356d3f5079efebfbe5a2e7348010be94f76b199c97d65d4727ee4fa7e6726350"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
