# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04329 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.29"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.29/cli_0.43.29_darwin_amd64.tar.gz"
      sha256 "321bbbada13eae2f79b4fa0243eb1ee71e2de6247172cb5e35af32b502d8ce60"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.29/cli_0.43.29_darwin_arm64.tar.gz"
      sha256 "81dbd6aff24a4d1e0b74bfd7b7ac671aaf513a91439ab0c1b83c801b50dc323b"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.29/cli_0.43.29_linux_amd64.tar.gz"
        sha256 "b216ea985690ebc7b01b82548ee72ce07444a5211947ae5eb35190d57ad8ef11"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.29/cli_0.43.29_linux_armv6.tar.gz"
        sha256 "34a94d3e6d0e20e4bb1d161a0bd7f14082bf6e30046cc7b7b434b944a1776504"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.29/cli_0.43.29_linux_arm64.tar.gz"
        sha256 "7b2e9501e756e9c1c5ada4a65b76923276729a137bde40eada90081107b85686"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
