# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT03621 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.21"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.21/infisical_0.36.21_darwin_amd64.tar.gz"
      sha256 "8b02faa4a475ea89e4f6e14deaff0cd76a6e6481bbea8555dca0cc31819c4e71"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.21/infisical_0.36.21_darwin_arm64.tar.gz"
      sha256 "4f48d3d92edb88e997a13264ccda6fd377f9b130c991df07d533b6998473b0c7"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.21/infisical_0.36.21_linux_amd64.tar.gz"
        sha256 "4b983be51a2311f6a4be52a3ffa4770090b9c01cb93ba4b76f4c7910417b3ed5"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.21/infisical_0.36.21_linux_armv6.tar.gz"
        sha256 "6375391bdf76ff3a8929f15987435d78ddc88993d63c12e89cd09a0376a1e1fb"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.21/infisical_0.36.21_linux_arm64.tar.gz"
        sha256 "f40467891e3f39206d79886ae808e9cf42e9ed9abe8d6af6c0a2f7021608524f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
