# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04389 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.89"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.89/cli_0.43.89_darwin_amd64.tar.gz"
    sha256 "28826054dd2bd258a6da3f05dfedab440978bc016144ea02c6905e8c193194ed"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.89/cli_0.43.89_darwin_arm64.tar.gz"
    sha256 "8e6b0f61c68d0f1e0b85be622582f63cf8c145ed37eb10db320fc4d01ec9e75f"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
