# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0426 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.42.6"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.42.6/cli_0.42.6_darwin_amd64.tar.gz"
      sha256 "ca6343829c36fec79c460e56ed011d9f47bcb8eaba39be01f2ae3455c4c3b326"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.42.6/cli_0.42.6_darwin_arm64.tar.gz"
      sha256 "c31c017d1c871bbc3fedd6848cb7b52b2281f8115c304d168f1c52da396364e7"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.6/cli_0.42.6_linux_amd64.tar.gz"
        sha256 "077a9aace7e4b3164181a8faa0c436c012f4975ed0f1b4268d12966167238722"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.6/cli_0.42.6_linux_armv6.tar.gz"
        sha256 "9d26ce28a7045a19cce87fd891071582d76fe1796d5963b084b483ea25d108f2"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.42.6/cli_0.42.6_linux_arm64.tar.gz"
        sha256 "7ffba21321dadd7fc7544a7310aee1a7144a37c8285a80a92833ce4be67b0aa0"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
