# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0430 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_darwin_amd64.tar.gz"
      sha256 "88dd1b2315cf2dc4608eee030f1a8981a93f80e3db65d2b3aa7eeeb542480a61"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_darwin_arm64.tar.gz"
      sha256 "6768ab1017423f6c6450563d23dd617426935efd56c4155244d5da05b2695c94"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_linux_amd64.tar.gz"
        sha256 "6fe9b91c0e79551c372ab6360ee6d8a49be7e933b20512977ed7c2f49f90c7de"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_linux_armv6.tar.gz"
        sha256 "3168a898a1e48c44157b9f94b5eca80fa42e6275aa5c84562f6499f04fabcb18"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.0/cli_0.43.0_linux_arm64.tar.gz"
        sha256 "2d5fa4724c54af058f38a6b51b529684d9f1dde6c7e496fd1d0d575aee08f8be"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
