# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04196 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.96"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.41.96/cli_0.41.96_darwin_amd64.tar.gz"
      sha256 "fb4506ea13daca79335552d211f773ef4f4bb36b6abf1fc8a45424e0f59b434a"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.41.96/cli_0.41.96_darwin_arm64.tar.gz"
      sha256 "ae11e4c347545def4f03eb1b1b104b4392d9e5a6ee1ab60a032abb98e60df82f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.96/cli_0.41.96_linux_amd64.tar.gz"
        sha256 "bcfbba296d201d8f1d0a477a14596151211955c3e8694d3d7347e8cfd918d67f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.96/cli_0.41.96_linux_armv6.tar.gz"
        sha256 "974cbfc96657a90f6c8aea04c41f5f31f347eeaa5111e28ed3a5494b1fecfc52"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.96/cli_0.41.96_linux_arm64.tar.gz"
        sha256 "0e0b85787e88c12f4c022d4b3abd77906b8b3b6c7c271448d8143d1a32b065a8"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
