# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043135 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.135"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.135/cli_0.43.135_darwin_amd64.tar.gz"
    sha256 "d1b0bf4e4b8dab00a90b2c2b4897f20f19afd446a0d903683ded993a48282f35"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.135/cli_0.43.135_darwin_arm64.tar.gz"
    sha256 "0f4ef95ad3ced6665f22625f8643c7dacf7c4b0f60104193bcb6d7f83261ef1e"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
