# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0380 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.38.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.38.0/infisical_0.38.0_darwin_amd64.tar.gz"
      sha256 "3812d9c76d86524469aac791ebf9116eb05f468008eab4f1d8baa588aa4b6c4b"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.38.0/infisical_0.38.0_darwin_arm64.tar.gz"
      sha256 "5709b6b7e321a961edc53a699fe284cc144f51923e12fa96b776ba52e7c81e6b"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.38.0/infisical_0.38.0_linux_amd64.tar.gz"
        sha256 "331a58e885510bbd09cc6aae07a693d8f08c39d745101d58e1f916bd273f544d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.38.0/infisical_0.38.0_linux_armv6.tar.gz"
        sha256 "55d6edcffacb8f33d8f0bbd8dfd232923dc56745fb66ad44f1e1dfbf958533dc"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.38.0/infisical_0.38.0_linux_arm64.tar.gz"
        sha256 "fe6ba00ab6d60abdd2f3a5098a6f17de8b916e24f6173bca22f61e0f290efdbe"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
