# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043128 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.128"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.128/cli_0.43.128_darwin_amd64.tar.gz"
    sha256 "9a935147836d5bc55f979b1d376075a82a905015f1d825a161a6e93d71f0da26"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.128/cli_0.43.128_darwin_arm64.tar.gz"
    sha256 "ba56365e3d34d79db1b9d145e1ba965bb1b1b421983b255a1d7cbe70f168c8ca"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
