# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT03612 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.36.12"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.12/infisical_0.36.12_darwin_amd64.tar.gz"
      sha256 "3016f0de655f3482c6f4b9acb79f4710a90f152609b7f7a9528875285bdac984"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.12/infisical_0.36.12_darwin_arm64.tar.gz"
      sha256 "1047cc32c940f48f864524792898242388b8c91b7c064a9a25730567e2ad9b8f"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.12/infisical_0.36.12_linux_amd64.tar.gz"
        sha256 "2359f86e6fe34faa057b1900a218ecaed4c8eecf21e9476793920b23fbbc50ff"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.12/infisical_0.36.12_linux_armv6.tar.gz"
        sha256 "089f3765ac030524968a44769b9bc916cabded13f25bc074e8eb6178b586620f"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.36.12/infisical_0.36.12_linux_arm64.tar.gz"
        sha256 "a1ce7233eab1e95b3a9109b9b4cedd0d92ff05d2f349f2f31f127a3a12357638"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
