# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04192 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.41.92"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.41.92/cli_0.41.92_darwin_amd64.tar.gz"
      sha256 "70867c9fbe711850816de9090a0f9af34c8c43c03abac0c5f0d57c3448a2039d"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.41.92/cli_0.41.92_darwin_arm64.tar.gz"
      sha256 "0e86add509c1d703f57079434b8bf5f9ca7d5822f2e4839de89a362067ed3f54"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.92/cli_0.41.92_linux_amd64.tar.gz"
        sha256 "b5d91e12d3eedba589dba4d492ed128a4d775e608b8084fa79d4b43a95e5a4a1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.92/cli_0.41.92_linux_armv6.tar.gz"
        sha256 "eb1ae654c9c205c47019d910b2398a2cdbabdb7479e730ed678fd8139ef502c1"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.41.92/cli_0.41.92_linux_arm64.tar.gz"
        sha256 "9e333acd5b44075431085bfba1aa5913a967b3e0ac4e029bc436cc31ceb51d17"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
