# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0141 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.14.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.1/infisical_0.14.1_darwin_arm64.tar.gz"
      sha256 "53c7492f5053f44d61b096da5f6d22f6bd137c070b22fa702548b30a06615fcd"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.1/infisical_0.14.1_darwin_amd64.tar.gz"
      sha256 "70592a908297c80933906b05a5ac03f6cd9248b1ef63169675bf85f7c83bf1bb"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.1/infisical_0.14.1_linux_arm64.tar.gz"
      sha256 "a96e4627ac23917b48186a8273dc883c84bcb2a886439fc0a7c6f4ad6079732e"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.1/infisical_0.14.1_linux_amd64.tar.gz"
      sha256 "b1fbc460985d314cd567eeb075f99374564843641e60bf0a9d018ab1d986a617"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.14.1/infisical_0.14.1_linux_armv6.tar.gz"
      sha256 "fc99945266a7a0d0aa82dc7f50f7b5f7ce94d1d727e7b990cc7714e5af1888ac"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
