# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0340 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.34.0"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.0/infisical_0.34.0_darwin_amd64.tar.gz"
      sha256 "5cfd368fce4c126f453bb42aecafa0c06563aa3250816df9f539e74b6e3c3c55"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.0/infisical_0.34.0_darwin_arm64.tar.gz"
      sha256 "5c6039b1e734714da3d9a39ba86e9d03362a68e609c278851281f3fd2db7dd92"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.0/infisical_0.34.0_linux_amd64.tar.gz"
        sha256 "3497288023d6216733bf4b176fa515c04b88dd6e7ad31ba91795ccbad8ed7a32"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.0/infisical_0.34.0_linux_armv6.tar.gz"
        sha256 "c3cbb66a539ff50835abe9e6d0d693b42de8cfd3119267bf12454c3ba1f5b18d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/infisical/releases/download/infisical-cli/v0.34.0/infisical_0.34.0_linux_arm64.tar.gz"
        sha256 "3b0af81de13e01b6ef06fa556f638b337abefb5ef330db84f215cb3d3f15a82b"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
