# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT043110 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.110"
  depends_on :macos

  on_intel do
    url "https://github.com/Infisical/cli/releases/download/v0.43.110/cli_0.43.110_darwin_amd64.tar.gz"
    sha256 "554f112ab68290059827395506c7f1f6386076925867d4160fa35b956fafa606"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
  on_arm do
    url "https://github.com/Infisical/cli/releases/download/v0.43.110/cli_0.43.110_darwin_arm64.tar.gz"
    sha256 "3cbcbffb2bd3e21c18eef8f90d256f0af6be5fbd2505f74a2896c2047007c0c6"

    def install
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
    end
  end
end
