# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04320 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.20"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.20/cli_0.43.20_darwin_amd64.tar.gz"
      sha256 "a4d7555c350c0173895fbf82ca89c1f05569039f27f643978eeb92887fc6c6e9"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.20/cli_0.43.20_darwin_arm64.tar.gz"
      sha256 "5d895ca9433d6bb9ba56bdd439b92309a862175446dee4e287475e53ad1ec4bc"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.20/cli_0.43.20_linux_amd64.tar.gz"
        sha256 "4b34366fb7e974b5f7e47d6e5be8197e2f30ed9e5251677edd07587a1c195c23"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.20/cli_0.43.20_linux_armv6.tar.gz"
        sha256 "6ed2301ae299324dd91f3b73fe21f418065d03d79d8da68551d2ac7071af7c54"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.20/cli_0.43.20_linux_arm64.tar.gz"
        sha256 "a6313bb5c44035c755181061725176fa0d5889687b3dfbf5880dbca174518481"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
