# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT0439 < Formula
  desc "The official Infisical CLI"
  homepage "https://infisical.com"
  version "0.43.9"

  on_macos do
    on_intel do
      url "https://github.com/Infisical/cli/releases/download/v0.43.9/cli_0.43.9_darwin_amd64.tar.gz"
      sha256 "caba93b0c2229301a3643d42c0ee5e73a1139115bcf6fcf2f7b36416e51ce4c1"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Infisical/cli/releases/download/v0.43.9/cli_0.43.9_darwin_arm64.tar.gz"
      sha256 "a799b65becdcf7ed91132bbf9b59b88387f579f421ffe8c410060aed916e4a3c"

      def install
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.9/cli_0.43.9_linux_amd64.tar.gz"
        sha256 "354b0ea19179447b8a2fc316277d9aab441436c2b7fe8a20a4b30ff8fb33ab0d"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.9/cli_0.43.9_linux_armv6.tar.gz"
        sha256 "cc6f1c3e8469d40e4b796ca40ce2f4ee7881323294dc0303866f363de7ecc47e"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Infisical/cli/releases/download/v0.43.9/cli_0.43.9_linux_arm64.tar.gz"
        sha256 "36b5f9c47dd0f4f2ed793041ca63dff8b25ffad4f951f4406cae61766fa534d6"

        def install
          bin.install "infisical"
          bash_completion.install "completions/infisical.bash" => "infisical"
          zsh_completion.install "completions/infisical.zsh" => "_infisical"
          fish_completion.install "completions/infisical.fish"
          man1.install "manpages/infisical.1.gz"
        end
      end
    end
  end
end
